### DISCUSSION TITLE
Proper way to configure reverse proxy header configuration with Traefik K3S

### DISCUSSION THREAD

**Discussion by 93imagine** [nextcloud/helm#512] [Q&A]
Hi! First of all, thanks for reading!

I'm trying to get Nextcloud working properly behind a Traefik Ingress Controller in a K3S cluster. I think I am confused about the proper way to set this up and I hope someone could show me a working example.

There errors I'm hoping to fix are:
- The reverse proxy header configuration is incorrect. This is a security issue and can allow an attacker to spoof their IP address as visible to the Nextcloud. For more details see the [documentation ↗](https://docs.nextcloud.com/server/28/go.php?to=admin-reverse-proxy).
-     You are accessing your instance over a secure connection, however your instance is generating insecure URLs. This most likely means that you are behind a reverse proxy and the overwrite config variables are not set correctly. Please read [the documentation page about this ↗](https://docs.nextcloud.com/server/28/go.php?to=admin-reverse-proxy).

I am deploying the helm chart through ArgoCD and most is working. My latest attempt was using the labels option I spotted (seemed like what I needed).

```yaml
    values: |
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: letsencrypt
        tls:
          - secretName: nextcloud-tls
            hosts:
              - url-that-works-fine
        labels: 
          traefik.http.routers.nextcloud.middlewares: 'nextcloud_redirectregex'
          traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent: true
          traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex: 'https://(.*)/.well-known/(?:card|cal)dav'
          traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement: 'https://$${1}/remote.php/dav'
        path: /
        pathType: Prefix 
```

I have also tried installing the middleware sepately and setting: 
`traefik.ingress.kubernetes.io/router.middlewares: nextcloud-nextcloud-redirectregex@kubernetescrd,nextcloud-nextcloud-headers@kubernetescrd`

Could anyone explain me what the proper way to set these settings using helm is? 

Thanks!
