### DISCUSSION TITLE
Can't access my nextcloud

### DISCUSSION THREAD

**Discussion by Rafael-Schippers** [nextcloud/helm#578] [Q&A]
I wanted to try out nextcloud on kubernetes so I crafted a values.yaml file and applied it the command `helm install -n nextcloud-test nextcloud-test -f values.yaml nextcloud/nextcloud` but I still can't access the webpage. This is how my values.yaml file looks like

```yaml
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  pathType: Prefix

internalDatabase:
  enabled: false

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: "postgressuser"
        password: "postgresspass"
        database: "nextcloud"
  primary:
    persistence:
      enabled: true
      existingClaim: "data-nextcloud-test-postgresql-0"
      storageClass: "netapp-volume"

externalDatabase:
  enabled: true
  type: postgresql
  host: nextcloud-test-postgresql.nextcloud-test.svc.cluster.local
  user: "postgressuser"
  password: "postgresspass"
  database: "nextcloud"

nextcloud:
  host: nextcloud-test.foo.com
  username: nextcloudadmin
  password: somepass
  configs:
    logging.config.php: |-
      <?php
      $CONFIG = array (
        'log_type' => 'file',
        'logfile' => '/var/log/nextcloud.log',
        'loglevel' => 0,
        'logdateformat' => 'F d, Y H:i:s',
        );
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array(
          0 => '192.168.93.2',
          1 => '192.168.93.3',
        )
      );

persistence:
  enabled: true
  storageClass: netapp-volume
  size: 100Gi

livenessProbe:
  enabled: false
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: false
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
```
Sometimes the pods also don't work and sometimes they do work... here is the log of postgres when it doesn't work.

```logtalk
postgresql 12:29:45.42 INFO  ==> ** Starting PostgreSQL **
2024-05-31 12:29:45.451 GMT [1] LOG:  skipping missing configuration file "/bitnami/postgresql/data/postgresql.auto.conf"
postgres: could not find the database system
Expected to find it in the directory "/bitnami/postgresql/data",
but could not open file "/bitnami/postgresql/data/global/pg_control": No such file or directory
```
