### DISCUSSION TITLE
[solved] Gateway Timeout in Adroid App for large Uploads, MOVE 499

### DISCUSSION THREAD

**Discussion by poggenpower** [nextcloud/helm#591] [Q&A] [answered]
Deployed Nexcloud behind a [project contour ingress controller/HTTPProxy](https://projectcontour.io/) which is based on Envoy. And deployed Nexclound in FPM mode. 
When uploading large files > 2GB via Android App (many chunks) the MOVE operation after > 50 PUT to create final file tooks more than 15 sec. This caused the contour to close the connection and the App showed a failed upload with status "Unknown Errror" or "Gateway timeout".
The Nginx log showed a `MOVE` action with Status Code `499`.
To get better error logging I added:
```yaml
  config:
    custom: |-
      error_log /dev/stdout info;
```
which logs a more detailed error message, which gives clear indication, that the problem is the client side of the connection:
```logtalk
2024/07/14 21:16:40 [info] 24#24: *94 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 172.16.248.98, server: , request: "MOVE /remote.php/dav/uploads/thl/38116e6348c8ba7cc4dedcac3958092e/.file HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "fez.aaaaa.ee"
```
As the client is routed through a contour ingress controller/HTTPProxy, the client connection from nginx perspective is not the andrid app, but the HTTPProxy.
By default the HTTPProxy (AFAIK any envoy) has a response timeout of 15 seconds, which is to short to process those 50 chunks in my environment. 
```yaml
  routes:
    - conditions:
      - prefix: /
      services: 
        - name: nextcloud
          port: 8080
      timeoutPolicy:
        response: 180s
```
adding a `timeoutPolicy.response=180s` gives now enough time to wait for longer tasks. 
If you using the standard Ingres Controller from project contour and not the HTTPProxy you can extend the timeout, by adding an annotation. 

Leaving this here, as I have not found any information about this issue when searing the net and this may now the place were other get the right hint. 
IMHO error messages from nginx to stdout should be a standard, to give better context when something going wrong.
