### DISCUSSION TITLE
Nextcloud container quits on initializing?

### DISCUSSION THREAD

**Discussion by DaanSelen** [nextcloud/helm#635] [Q&A]
```shell
<user>@<machine>:~/k8s/dev$ k logs -f test-nextcloud-5fbc87c77f-nkbxg
Defaulted container "nextcloud" out of: nextcloud, postgresql-isready (init)
Initializing nextcloud 30.0.0.14 ...
New nextcloud instance
Installing with PostgreSQL database
=> Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/pre-installation
Starting nextcloud installation
<user>@<machine>:~/k8s/dev$ k logs -f test-nextcloud-5fbc87c77f-nkbxg
Defaulted container "nextcloud" out of: nextcloud, postgresql-isready (init)
=> Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.216.224.114. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.216.224.114. Set the 'ServerName' directive globally to suppress this message
[Tue Sep 24 13:31:10.892865 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.2.23 configured -- resuming normal operations
[Tue Sep 24 13:31:10.892897 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
172.16.41.51 - - [24/Sep/2024:13:31:20 +0000] "GET /status.php HTTP/1.1" 200 1663 "-" "kube-probe/1.30"
172.16.41.51 - - [24/Sep/2024:13:31:20 +0000] "GET /status.php HTTP/1.1" 200 1665 "-" "kube-probe/1.30"
172.16.41.51 - - [24/Sep/2024:13:31:30 +0000] "GET /status.php HTTP/1.1" 200 1653 "-" "kube-probe/1.30"
172.16.41.51 - - [24/Sep/2024:13:31:30 +0000] "GET /status.php HTTP/1.1" 200 1655 "-" "kube-probe/1.30"
```

Why does it restart?

**Comment by DaanSelen** [comment]
Also maybe a sidenode. But I am unable to get it running using the default example/test nextcloud user and changme password. It still asks me for the "Create a new admin user" on nextcloud page, but the tables are already created on Postgres...

**Comment by provokateurin** [comment]
I don't see an initialization failure? Also the 200 status logs indicate the probes confirm that everything went fine?

**Reply by DaanSelen** [reply]
You can see in the middle of the original post that the logging suddenly ends, and I have to recall the command to continue.
Line 8.

**Reply by provokateurin** [reply]
Ah sorry I didn't see that.
This is likely the container getting killed because the database is not up yet.
The container then restarts and once the database is available it does the initialization.
It looks fine to me.

**Reply by DaanSelen** [reply]
Then the question I have after this, I used the official chart and the postgres database in there. And when I check the postgres database, I see all the OCC tables present. But when I go to the nextcloud webpage, it asks me to create an admin user, which should exist according to the chart right?

**Reply by provokateurin** [reply]
Hm yes that should be present. Please note this chart is not "official", it is maintained by the community.

**Reply by DaanSelen** [reply]
I will try to recreate it on my home cluster. And show you what I mean. Tomorrow

**Reply by DaanSelen** [reply]
@provokateurin perhaps can I mail you the screenshots, or if you prefer I can post a big threat response here.

**Reply by provokateurin** [reply]
Just put them down here, so everyone can see them (but please redact any private/sensitive information).

**Reply by DaanSelen** [reply]
I used this values.yaml for the deployment:
```yaml
## Official nextcloud image version
## ref: https://hub.docker.com/r/library/nextcloud/tags/
##
image:
  repository: nextcloud
  flavor: apache
  # default is generated by flavor and appVersion
  tag:
  pullPolicy: IfNotPresent
  # pullSecrets:
  #   - myRegistrKeySecretName

nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
deploymentAnnotations: {}
deploymentLabels: {}

# Number of replicas to be deployed
replicaCount: 1

# Allow configuration of lifecycle hooks
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/
lifecycle: {}
  # postStartCommand: []
  # preStopCommand: []

phpClientHttpsFix:
  enabled: false
  protocol: https

nextcloud:
  host: 172.16.41.61
  username: admin
  password: changeme
  ## Use an existing secret
  existingSecret:
    enabled: false
    # secretName: nameofsecret
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
    tokenKey: ""
    smtpUsernameKey: smtp-username
    smtpPasswordKey: smtp-password
    smtpHostKey: smtp-host
  update: 0
  # If web server is not binding default port, you can define it
  containerPort: 80
  datadir: /var/www/html/data
  persistence:
    subPath:
  # if set, we'll template this list to the NEXTCLOUD_TRUSTED_DOMAINS env var
  trustedDomains: []

  ## PHP Configuration files
  # Will be injected in /usr/local/etc/php/conf.d for apache image and in /usr/local/etc/php-fpm.d when nginx.enabled: true
  phpConfigs: {}
  ## Default config files that utilize environment variables:
  # see: https://github.com/nextcloud/docker/tree/master#auto-configuration-via-environment-variables
  # IMPORTANT: Will be used only if you put extra configs, otherwise default will come from nextcloud itself
  # Default confgurations can be found here: https://github.com/nextcloud/docker/tree/master/.config
  defaultConfigs:
    # To protect /var/www/html/config
    .htaccess: true
    # Apache configuration for rewrite urls
    apache-pretty-urls.config.php: true
    # Define APCu as local cache
    apcu.config.php: true
    # Apps directory configs
    apps.config.php: true
    # Used for auto configure database
    autoconfig.php: false
    # Redis default configuration
    redis.config.php: false
    # Reverse proxy default configuration
    reverse-proxy.config.php: true
    # S3 Object Storage as primary storage
    s3.config.php: true
    # SMTP default configuration via environment variables
    smtp.config.php: true
    # Swift Object Storage as primary storage
    swift.config.php: true
    # disables the web based updater as the default nextcloud docker image does not support it
    upgrade-disable-web.config.php: true

  # Extra config files created in /var/www/html/config/
  # ref: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file
  configs: {}
  # For example, to enable image and text file previews:
  #  previews.config.php: |-
  #    <?php
  #    $CONFIG = array (
  #      'enable_previews' => true,
  #      'enabledPreviewProviders' => array (
  #        'OC\Preview\Movie',
  #        'OC\Preview\PNG',
  #        'OC\Preview\JPEG',
  #        'OC\Preview\GIF',
  #        'OC\Preview\BMP',
  #        'OC\Preview\XBitmap',
  #        'OC\Preview\MP3',
  #        'OC\Preview\MP4',
  #        'OC\Preview\TXT',
  #        'OC\Preview\MarkDown',
  #        'OC\Preview\PDF'
  #      ),
  #    );

  # Hooks for auto configuration
  # Here you could write small scripts which are placed in `/docker-entrypoint-hooks.d/<hook-name>/helm.sh`
  # ref: https://github.com/nextcloud/docker?tab=readme-ov-file#auto-configuration-via-hook-folders
  hooks:
    pre-installation:
    post-installation:
    pre-upgrade:
    post-upgrade:
    before-starting:

  ## Strategy used to replace old pods
  ## IMPORTANT: use with care, it is suggested to leave as that for upgrade purposes
  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  strategy:
    type: Recreate
    # type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 1
    #   maxUnavailable: 0

  ##
  ## Extra environment variables
  extraEnv:
  #  - name: SOME_SECRET_ENV
  #    valueFrom:
  #      secretKeyRef:
  #        name: nextcloud
  #        key: secret_key

  # Extra init containers that runs before pods start.
  extraInitContainers: []
  #  - name: do-something
  #    image: busybox
  #    command: ['do', 'something']

  # Extra sidecar containers.
  extraSidecarContainers: []
  #  - name: nextcloud-logger
  #    image: busybox
  #    command: [/bin/sh, -c, 'while ! test -f "/run/nextcloud/data/nextcloud.log"; do sleep 1; done; tail -n+1 -f /run/nextcloud/data/nextcloud.log']
  #    volumeMounts:
  #    - name: nextcloud-data
  #      mountPath: /run/nextcloud/data

  # Extra mounts for the pods. Example shown is for connecting a legacy NFS volume
  # to NextCloud pods in Kubernetes. This can then be configured in External Storage
  extraVolumes:
  #  - name: nfs
  #    nfs:
  #      server: "10.0.0.1"
  #      path: "/nextcloud_data"
  #      readOnly: false
  extraVolumeMounts:
  #  - name: nfs
  #    mountPath: "/legacy_data"

  # Set securityContext parameters for the nextcloud CONTAINER only (will not affect nginx container).
  # For example, you may need to define runAsNonRoot directive
  securityContext: {}
  #   runAsUser: 33
  #   runAsGroup: 33
  #   runAsNonRoot: true
  #   readOnlyRootFilesystem: false

  # Set securityContext parameters for the entire pod. For example, you may need to define runAsNonRoot directive
  podSecurityContext: {}
  #   runAsUser: 33
  #   runAsGroup: 33
  #   runAsNonRoot: true
  #   readOnlyRootFilesystem: false

  # Settings for the MariaDB init container
  mariaDbInitContainer:
    # Set mariadb initContainer securityContext parameters. For example, you may need to define runAsNonRoot directive
    securityContext: {}

  # Settings for the PostgreSQL init container
  postgreSqlInitContainer:
    # Set postgresql initContainer securityContext parameters. For example, you may need to define runAsNonRoot directive
    securityContext: {}

internalDatabase:
  enabled: false
  name: nextcloud

##
## External database configuration
##
externalDatabase:
  enabled: true

  ## Supported database engines: mysql or postgresql
  type: postgresql

  ## Database host
  host: "test-postgresql:5432"

  ## Database user
  user: nextcloud

  ## Database password
  password: "changeme"

  ## Database name
  database: nextcloud

  ## Use a existing secret
  existingSecret:
    enabled: false
    # secretName: nameofsecret
    usernameKey: db-username
    passwordKey: db-password
    # hostKey: db-hostname-or-ip
    # databaseKey: db-name

##
## PostgreSQL chart configuration
## for more options see https://github.com/bitnami/charts/tree/main/bitnami/postgresql
##
postgresql:
  enabled: true
  global:
    postgresql:
      # global.postgresql.auth overrides postgresql.auth
      auth:
        username: nextcloud
        password: "changeme"
        database: nextcloud
        # Name of existing secret to use for PostgreSQL credentials.
        # auth.postgresPassword, auth.password, and auth.replicationPassword will be ignored and picked up from this secret.
        # secret might also contains the key ldap-password if LDAP is enabled.
        # ldap.bind_password will be ignored and picked from this secret in this case.
        existingSecret: ""
        # Names of keys in existing secret to use for PostgreSQL credentials
        secretKeys:
          adminPasswordKey: ""
          userPasswordKey: ""
          replicationPasswordKey: ""
  primary:
    persistence:
      enabled: true
      # Use an existing Persistent Volume Claim (must be created ahead of time)
      # existingClaim: ""
      # storageClass: ""

##
## Redis chart configuration
## for more options see https://github.com/bitnami/charts/tree/main/bitnami/redis
##

redis:
  enabled: false
  auth:
    enabled: true
    password: 'changeme'
    # name of an existing secret with Redis® credentials (instead of auth.password), must be created ahead of time
    existingSecret: ""
    # Password key to be retrieved from existing secret
    existingSecretPasswordKey: ""
  # Since Redis is used for caching only, you might want to use a storageClass with different reclaim policy and backup settings
  global:
    storageClass: ""
  master:
    persistence:
      enabled: true
  replica:
    persistence:
      enabled: true


## Cronjob to execute Nextcloud background tasks
## ref: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron
##
cronjob:
  enabled: false

  ## Cronjob sidecar resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}

  # Allow configuration of lifecycle hooks
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/
  lifecycle: {}
    # postStartCommand: []
    # preStopCommand: []
  # Set securityContext parameters. For example, you may need to define runAsNonRoot directive
  securityContext: {}
  #   runAsUser: 33
  #   runAsGroup: 33
  #   runAsNonRoot: true
  #   readOnlyRootFilesystem: true

service:
  type: LoadBalancer
  port: 8080
  #loadBalancerIP: "172.16.41.61"
  #nodePort:
  annotations: { metallb.universe.tf/loadBalancerIPs: 172.16.41.61 }
    ## Insert your annotations such as below
    # test/test: pumuckel

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  # Nextcloud Data (/var/www/html)
  enabled: true
  annotations: {}
  ## nextcloud data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  accessMode: ReadWriteOnce
  size: 10Gi

  ## Use an additional pvc for the data directory rather than a subpath of the default PVC
  ## Useful to store data on a different storageClass (e.g. on slower disks)
  nextcloudData:
    enabled: true
    subPath:
    annotations: {}
    # storageClass: "-"
    # existingClaim:
    accessMode: ReadWriteOnce
    size: 10Gi

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

## Liveness and readiness probe values
## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
##
livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
  successThreshold: 1


## Enable pod autoscaling using HorizontalPodAutoscaler
## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
##
hpa:
  enabled: false
  cputhreshold: 60
  minPods: 1
  maxPods: 10

nodeSelector: {}

tolerations: []

affinity: {}

dnsConfig: {}
# Custom dns config for Nextcloud containers.
# You can for example configure ndots. This may be needed in some clusters with alpine images.
# options:
#   - name: ndots
#     value: "1"

## Prometheus Exporter / Metrics
##
metrics:
  enabled: false

  replicaCount: 1
  # Optional: becomes NEXTCLOUD_SERVER env var in the nextcloud-exporter container.
  # Without it, we will use the full name of the nextcloud service
  server: ""
  # The metrics exporter needs to know how you serve Nextcloud either http or https
  https: false
  # Use API token if set, otherwise fall back to password authentication
  # https://github.com/xperimental/nextcloud-exporter#token-authentication
  # Currently you still need to set the token manually in your nextcloud install
  token: ""
  timeout: 5s
  # if set to true, exporter skips certificate verification of Nextcloud server.
  tlsSkipVerify: false
  info:
    # Optional: becomes NEXTCLOUD_INFO_APPS env var in the nextcloud-exporter container.
    # Enables gathering of apps-related metrics. Defaults to false
    apps: false

  image:
    repository: xperimental/nextcloud-exporter
    tag: 0.6.2
    pullPolicy: IfNotPresent
    # pullSecrets:
    #   - myRegistrKeySecretName

  ## Metrics exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}

  # -- Metrics exporter pod Annotation
  podAnnotations: {}

  # -- Metrics exporter pod Labels
  podLabels: {}

  # -- Metrics exporter pod nodeSelector
  nodeSelector: {}

  # -- Metrics exporter pod tolerations
  tolerations: []

  # -- Metrics exporter pod affinity
  affinity: {}

  service:
    type: ClusterIP
    # Use serviceLoadBalancerIP to request a specific static IP,
    # otherwise leave blank
    loadBalancerIP:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9205"
    labels: {}

  # -- security context for the metrics CONTAINER in the pod
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    # allowPrivilegeEscalation: false
    # capabilities:
    #   drop:
    #     - ALL

  # -- security context for the metrics POD
  podSecurityContext: {}
  # runAsNonRoot: true
  # seccompProfile:
  #   type: RuntimeDefault

  ## Prometheus Operator ServiceMonitor configuration
  ##
  serviceMonitor:
    ## @param metrics.serviceMonitor.enabled Create ServiceMonitor Resource for scraping metrics using PrometheusOperator
    ##
    enabled: false

    ## @param metrics.serviceMonitor.namespace Namespace in which Prometheus is running
    ##
    namespace: ""

    ## @param metrics.serviceMonitor.namespaceSelector The selector of the namespace where the target service is located (defaults to the release namespace)
    namespaceSelector:

    ## @param metrics.serviceMonitor.jobLabel The name of the label on the target service to use as the job name in prometheus.
    ##
    jobLabel: ""

    ## @param metrics.serviceMonitor.interval Interval at which metrics should be scraped
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    ##
    interval: 30s

    ## @param metrics.serviceMonitor.scrapeTimeout Specify the timeout after which the scrape is ended
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    ##
    scrapeTimeout: ""

    ## @param metrics.serviceMonitor.labels Extra labels for the ServiceMonitor
    ##
    labels: {}


rbac:
  enabled: false
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount
    annotations: {}


## @param securityContext for nextcloud pod @deprecated Use `nextcloud.podSecurityContext` instead
securityContext: {}
```
I deploy it like:
```
~/k8s/dev$ helm install test nextcloud/nextcloud --values nextcloud-values.yaml
NAME: test
LAST DEPLOYED: Wed Sep 25 13:58:19 2024
NAMESPACE: next-dev
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the nextcloud URL by running:

  echo http://172.16.41.61/

2. Get your nextcloud login credentials by running:

  echo User:     admin
  echo Password: $(kubectl get secret --namespace next-dev test-nextcloud -o jsonpath="{.data.nextcloud-password}" | base64 --decode)
```
Then
```
~/k8s/dev$ k get pods
NAME                              READY   STATUS    RESTARTS   AGE
test-nextcloud-5fbc87c77f-cmfcw   0/1     Running   0          58s
test-postgresql-0                 1/1     Running   0          58s
```
This is the point where the container quits and restarts, and gives this as its logs:
```
~/k8s/dev$ k logs -f test-nextcloud-5fbc87c77f-cmfcw
\Defaulted container "nextcloud" out of: nextcloud, postgresql-isready (init)
=> Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.216.224.122. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.216.224.122. Set the 'ServerName' directive globally to suppress this message
[Wed Sep 25 11:59:39.151115 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.2.23 configured -- resuming normal operations
[Wed Sep 25 11:59:39.151156 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
172.16.41.51 - - [25/Sep/2024:11:59:48 +0000] "GET /status.php HTTP/1.1" 200 1649 "-" "kube-probe/1.30"
172.16.41.51 - - [25/Sep/2024:11:59:48 +0000] "GET /status.php HTTP/1.1" 200 1653 "-" "kube-probe/1.30"
172.16.41.51 - - [25/Sep/2024:11:59:58 +0000] "GET /status.php HTTP/1.1" 200 1657 "-" "kube-probe/1.30"
172.16.41.51 - - [25/Sep/2024:11:59:58 +0000] "GET /status.php HTTP/1.1" 200 1653 "-" "kube-probe/1.30"
172.16.41.51 - - [25/Sep/2024:12:00:08 +0000] "GET /status.php HTTP/1.1" 200 1655 "-" "kube-probe/1.30"
etc...
```
Then I get the create a admin screen (It's Dutch so excuse me for that)
![image](https://github.com/user-attachments/assets/99c6fa89-95d4-4f26-a852-926f705f7c97)
The name I declared in the yaml, is used so I cannot use that.
And when I create a new admin user per instruction of the GUI and click install:
```
~/k8s/dev$ k logs -f test-nextcloud-5fbc87c77f-cmfcw
Defaulted container "nextcloud" out of: nextcloud, postgresql-isready (init)
=> Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.216.224.122. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.216.224.122. Set the 'ServerName' directive globally to suppress this message
[Wed Sep 25 12:02:40.332772 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.2.23 configured -- resuming normal operations
[Wed Sep 25 12:02:40.332833 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
172.16.41.51 - - [25/Sep/2024:12:02:58 +0000] "GET /status.php HTTP/1.1" 400 1416 "-" "kube-probe/1.30"
172.16.41.51 - - [25/Sep/2024:12:02:58 +0000] "GET /status.php HTTP/1.1" 400 1408 "-" "kube-probe/1.30"
172.16.41.51 - - [25/Sep/2024:12:03:08 +0000] "GET /status.php HTTP/1.1" 400 1410 "-" "kube-probe/1.30"
172.16.41.51 - - [25/Sep/2024:12:03:08 +0000] "GET /status.php HTTP/1.1" 400 1416 "-" "kube-probe/1.30"
172.16.41.51 - - [25/Sep/2024:12:03:18 +0000] "GET /status.php HTTP/1.1" 400 1426 "-" "kube-probe/1.30"
172.16.41.51 - - [25/Sep/2024:12:03:18 +0000] "GET /status.php HTTP/1.1" 400 1414 "-" "kube-probe/1.30"
[Wed Sep 25 12:03:18.832810 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00170: caught SIGWINCH, shutting down gracefully
172.16.41.51 - - [25/Sep/2024:12:03:18 +0000] "GET /status.php HTTP/1.1" 400 1414 "-" "kube-probe/1.30"
```
This happends every time I try to poll the webpage.

Do you have any suggestions or documents to point me to? The log is not very helpful. Further info:
The postgres tables:
```
I have no name!@test-postgresql-0:/$ psql -U nextcloud
Password for user nextcloud:
psql (16.3)
Type "help" for help.

nextcloud=> \dt
                    List of relations
 Schema |            Name             | Type  |   Owner
--------+-----------------------------+-------+-----------
 public | oc_accounts                 | table | nextcloud
 public | oc_accounts_data            | table | nextcloud
 public | oc_activity                 | table | nextcloud
 public | oc_activity_mq              | table | nextcloud
 public | oc_addressbookchanges       | table | nextcloud
 public | oc_addressbooks             | table | nextcloud
 public | oc_appconfig                | table | nextcloud
 public | oc_authorized_groups        | table | nextcloud
 public | oc_authtoken                | table | nextcloud
 public | oc_bruteforce_attempts      | table | nextcloud
 public | oc_calendar_invitations     | table | nextcloud
 public | oc_calendar_reminders       | table | nextcloud
 public | oc_calendar_resources       | table | nextcloud
```
Thank you for reading... it is a lot.

**Comment by joshtrichards** [comment]
> `Starting nextcloud installation`

That's weird. 

You can see what is supposed to happen after that by looking here:

https://github.com/nextcloud/docker/blob/d03da64ac80d534c1b0ec69da3e6ddcc6af282a6/docker-entrypoint.sh#L225

I recently worked on adding a "verbose installation + debug mode" to the image entrypoint in nextcloud/docker#2311. 

It *might* be helpful in tracking down whatever is going on here (it's not released yet unfortunately, but if you feel up to manually building an image you can pull down the modified `Dockerfile` + `entrypoint.sh` from that PR's branch).

**Reply by DaanSelen** [reply]
I'll into that!

**Comment by papierkorp** [comment]
I had a similiar problem, my ceph storage was too slow and then the livenessProbe kicked in and restartet the pod. Like this the installation could never finish since its always restarting. The `solution` was to disable all of the probes for the Installation:

```yaml
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false
  ```
  
  and enable them afterwards. It should be enough to disable livenessProbe or you can also adjust the liveness Probe to get more time.
