### DISCUSSION TITLE
persistence.existingClaim not picking up the PVC

### DISCUSSION THREAD

**Discussion by bmarshallbri** [nextcloud/helm#655] [Q&A]
I am trying to install on kube 1.29. I have the following defined in my helm values. 

```
persistence:
  enabled: true
  annotations: {}
  existingClaim: nextcloud-pvc
  accessMode: ReadWriteOnce
  size: 30Gi
  nextcloudData:
    enabled: false
```

And I have applied the follow to the cluster in the namespace nextcloud to create the PV and PVC

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: nextcloud-pvc
    namespace: nextcloud
  nfs:
    path: /mnt/ssd0/nextcloud
    server: jumbonium.server.marvon.lan
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeName: nextcloud-pv
```

For some reason it does not pick up the PVC when I apply the chart. The redis and mysql claims are working but not the nextcloud pod claim. 

Any help spotting what I'm missing or doing wrong would be greatly appreciated.
