### DISCUSSION TITLE
How to create custom Cron?

### DISCUSSION THREAD

**Discussion by ankur198** [nextcloud/helm#678] [Q&A]
Hello,
I am new to NC helm and do not understand how to add my own custom cron. I understand that on a linux system I can use crontab. Can anyone give me an example on how to create custom cron. Let's say to create cron for [PreviewGenerator](https://github.com/nextcloud/previewgenerator)

Thanks in advance

PS: I have enabled cron and a sidecar for cron is created

**Comment by mazinsfr** [comment]
This post may be old, but the answer could still be helpful to others.

---

I recommend using Imaginary, as it automatically generates previews whenever a new file is uploaded.
How to migrate from previewgenerator to imaginary: https://okxo.de/speed-up-nextcloud-preview-generation-with-imaginary/#rebuild-preview-files-for-all-images

Edit yout helm chart values:
```yaml
nextcloud:
  defaultConfigs:
    imaginary.config.php: true
    
imaginary:
  enabled: true
  replicaCount: 1
```
---
Editing cron jobs is not supported by the Helm chart for the moment.
This is how I add crons in my nextcloud instance:

- I use sidecar cron (it starts with root privileges because crond need root access)
```yaml
cronjob:
  enabled: true
  type: sidecar
```
- I create a configmap for crons (this is an example, add the nextcloud namespace):
FYI: the Helm chart applies the same volume mounts to both the Nextcloud container and the cron container within the pod.
```yaml
apiVersion: v1
metadata:
  name: nextcloud-cron
data:
  root: |
    0 1 * * * find /var/www/html/data/user1 -type f -exec chmod 644 {} \;
    0 1 * * * find /var/www/html/data/user1 -type d -exec chmod 755 {} \;
  www-data: |
    */5 * * * * php -f /var/www/html/cron.php
    0 2 * * * /var/www/html/occ files:scan --all
immutable: false
kind: ConfigMap
```
- I mount the configmap like this:
```yaml
nextcloud:
  extraVolumeMounts:
    - mountPath: /var/spool/cron/crontabs
      name: nextcloud-cron
  extraVolumes:
    - configMap:
        name: nextcloud-cron
```

Remember to restart your Nextcloud pod after each ConfigMap update to apply the new cron settings.
