### DISCUSSION TITLE
Migrate from single volume to seperate-data volume

### DISCUSSION THREAD

**Discussion by SchoolGuy** [nextcloud/helm#719] [Q&A] [answered]
I would love to migrate from a single-data volume to a separate-data volume setup and would love to know how to achieve this.

Current HelmChart persistence values:

```yaml
persistence:
  enabled: true
  storageClass: nfs-slow
```

New desired values:

```yaml
persistence:
  enabled: true
  storageClass: nfs-fast
  size: 20Gi
  nextcloudData:
    enabled: true
    storageClass: nfs-slow
    size: 4Ti
```

Since my NC is "old" my current single-directory looks much different from a new deployment of NC. As such I am inclined to believe that there may be more to process than what meets the eye. I am hit by #10 and as such, I do desire to do this move to take advantage of my NVMe-backed NFS for everything but the real data for the users.
