### ISSUE TITLE
Extra volume mounts have root permissions, nextcloud can't access them.

### ISSUE THREAD

**Issue by Couto** [nextcloud/helm#101]
Extra volumes declared in the values.yml file are successfully mounted in the nextcloud container, however, they are mounted with root:root permissions, therefore the Nextcloud instance can't access those folders, resulting in a popup notification saying "This operation is forbidden".

This simple configuration:
```yaml
  # Extra mounts for the pods. Example shown is for connecting a legacy NFS volume
  # to NextCloud pods in Kubernetes. This can then be configured in External Storage
  extraVolumes:
    - name: nfs-shared-files
      nfs:
        server: "<REDACTED>"
        path: "/volume1/Shared Files/"
        readOnly: false
  extraVolumeMounts:
    - name: nfs-shared-files
      mountPath: "/mnt/shared_files"
```

Results in the following:
<img width="1306" alt="Screenshot 2021-03-23 at 19 42 56" src="https://user-images.githubusercontent.com/165314/112208371-331f8080-8c10-11eb-9032-1fb4734047ca.png">
<img width="1302" alt="Screenshot 2021-03-23 at 19 43 08" src="https://user-images.githubusercontent.com/165314/112208400-39adf800-8c10-11eb-9877-2399c10cfda8.png">

Is there any property that I'm missing?
