### ISSUE TITLE
Nextcloued freezes when running the first time with persistant volumes

### ISSUE THREAD

**Issue by apannwitz** [nextcloud/helm#108]
Hi,

When I try to run nextcloud with persistant volume, it freezed with:

Configuring Redis as session handler
15.4.2021 21:31:46 Initializing nextcloud 19.0.3.1 ...

Here is my helm command:

```bash
helm install nextcloud nextcloud/nextcloud -f nextcloud-values.yaml --version 2.6.1  -n nextcloud \
--create-namespace --namespace nextcloud \
--set nextcloud.host=nextcloud.DOMAIN.net \
--set ingress.enabled=true \
--set ingress.annotations."kubernetes\.io/ingress\.class"=public  \
--set ingress.tls[0].hosts[0]=nextcloud.DOMAIN.net \
--set ingress.tls[0].secretName=wildcard-DOMAIN-net \
--set nextcloud.username=hostmaster \
--set nextcloud.password=***** \
--set nextcloud.mail.enabled=true \
--set nextcloud.mail.domain=DOMAIN.com \
--set nextcloud.mail.fromAddress=hostmaster@DOMAIN.com \
--set nextcloud.mail.smtp.host=mail.DOMAIN.net \
--set nextcloud.mail.smtp.authtype=LOGIN \
--set nextcloud.mail.smtp.name=k8s-DOMAIN-mailrelay \
--set nextcloud.mail.smtp.password='**********' \
--set internalDatabase.enabled=false \
--set externalDatabase.enabled=true \
--set mariadb.enabled=true \
--set mariadb.db.name=nextcloud \
--set mariadb.db.password=********* \
--set mariadb.db.user=nextcloud \
--set mariadb.rootUser.password=******** \
--set mariadb.master.persistence.enabled=true \
--set mariadb.master.persistence.storageClass=nextcloud-pv-volume-mariadb \
--set mariadb.master.persistence.size=8Gi \
--set redis.enabled=true \
--set redis.usePassword=true \
--set redis.password=******* \
--set cronjob.enabled=true \
--set metrics.enabled=true \
--set metrics.https=true \
--set hpa.enabled=true \
--set persistence.enabled=true \
--set persistence.storageClass=nextcloud-pv-volume-data \
--set persistence.size=8Gi
```

Any suggestions?

Regards
Alex

**Comment by apannwitz** [comment]
Any hint?

**Comment by nebula2** [comment]
Same here. I observed the logs and this is what I see:
```
Initializing nextcloud 19.0.3.1 ...
rsync: ERROR: cannot stat destination "/var/www/html/": Stale file handle (116)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(660) [Receiver=3.1.3]
```

The Pod goes in CrashLoopBackOff and after that the story repeats

**Comment by uxes** [comment]
```
nextcloud:
  host: my.domain

service:
  type: ClusterIP

mariadb:
  enabled: true
  mariadb:
    master:
      persistence:
        storageClass: nfs1-mid
        size: 8Gi

persistence:
  enabled: true
  storageClass: nfs1-mid
  size: 20Gi

```

my pseudo solution was to ignore probes and wait until next morning
```
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

```
