### ISSUE TITLE
How do i override settings in the php.ini files?

### ISSUE THREAD

**Issue by sOblivionsCall** [nextcloud/helm#111]
This is more of a usage question than anything else for this helm chart. I am seeing the following error in my nginx ingress logs:

```
2021/04/26 03:11:34 [error] 3433#3433: *3414613 client intended to send too large body: 5024916 bytes, client: 10.1.1.199, server: xxx.xxx.com, request: "PUT /remote.php/dav/uploads/xxx.xxx/017ce9b160285657e87bfda4181479f2/0000000000000000-0000000005024916 HTTP/1.1", host: "xxx.xxx.com"
```

I have been trying to find a solution for this and think i have narrowed everything down to either the nginx ingress conf or the php.ini.

reference: https://help.nextcloud.com/t/files-not-getting-synced-413-request-entity-too-large/45681/4

I have set the ingress object in the helm chart to allow larger files:

```yaml
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issue-temporary-certificate: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        acme.cert-manager.io/http01-edit-in-place: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 10G
        nginx.ingress.kubernetes.io/proxy-buffer-size: "400M"
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
```

resulting in:

```
ame:             nextcloud
Namespace:        media
Address:          10.1.1.35
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
nextcloud-tls terminates xxx.xxx.com
Rules:
Host                         Path  Backends
----                         ----  --------
xxx.xxx.com
/   nextcloud:8080 (10.42.1.42:80)
Annotations:                   acme.cert-manager.io/http01-edit-in-place: true
cert-manager.io/cluster-issuer: letsencrypt-prod
cert-manager.io/issue-temporary-certificate: true
field.cattle.io/publicEndpoints:
[{"addresses":["10.1.1.35"],"port":443,"protocol":"HTTPS","serviceName":"media:nextcloud","ingressName":"media:nextcloud","hostname":"next...
kubernetes.io/ingress.class: nginx
kubernetes.io/tls-acme: true
meta.helm.sh/release-name: nextcloud
meta.helm.sh/release-namespace: media
nginx.ingress.kubernetes.io/proxy-body-size: 10G
nginx.ingress.kubernetes.io/proxy-buffer-size: 400M
Events:                        <none>
```

So as far as i can tell, the nginx config is correct. If i move the the path `/usr/local/etc/php` i see the following:

```bash
root@nextcloud-6f6df58c78-lgr2d:/usr/local/etc/php# ls
conf.d  php.ini-development  php.ini-production
```

From here my assumption is `post_max_size` and `upload_max_filesize` and set in `php.ini-production` which return the values:

```bash
root@nextcloud-6f6df58c78-lgr2d:/usr/local/etc/php# cat php.ini-production | grep post_max_size
post_max_size = 8M
root@nextcloud-6f6df58c78-lgr2d:/usr/local/etc/php# cat php.ini-production | grep upload_max_filesize
upload_max_filesize = 2M
```

i did a manual edit and restarted only to find them reverted back to the original value. So then i combed through the PVC and Deployment yamls to see that these files are not stored persistently. So now i do not understand how this helm chart intends for a user to set those values. 

Apologies if this is a very basic question but my PHP knowledge is next to zero so all the information i have is through trial and error at this point.
