### ISSUE TITLE
Spinning loader won't go away.

### ISSUE THREAD

**Issue by hlesesne** [nextcloud/helm#116]
I've recently tried to deploy this helm chart and everything seems be stood up ok and answering requests.

However, when I login to the application, I get a loading spinner over the initial files and it won't go away. Also, document previews seem to act the same way.

I'm assuming that I need to enable persistent storage or something and perhaps it is having trouble actually service files, but I just can't figure out the problem.

I looked at nextcloud's main repo and knowledgebase, and it seems that people have suggested that this behavior is due to using rich workspaces, but disabling them doesn't seem to make the problem go away.

myvalues.yaml
```yaml
fullnameOverride: hal-nextcloud
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: xxx.xxx.xxx.xxx/25,xxx.xxx.xxx.xxx/32
  enabled: true
  hosts:
  - host: hal-nextcloud.mydomain.org
    paths:
    - /
nextcloud:
  host: hal-nextcloud.mydomain.org
  username: admin
  password: foopassword
  extraEnv:
    - name: OVERWRITEPROTOCOL
      value: https
mariadb:
  enabled: true
  db:
    name: nextcloud
    user: nextcloud
    password: foopassword
  rootUser:
    password: foopassword
```    
Any suggestions or maybe a point in the right direction would be greatly appreciated and please let me know if there is any additional information I can provide. Thanks to the maintainers for such providing this chart, it makes deployment trivial (I just can't get past this UI problem).
