### ISSUE TITLE
How to create from Helm Charts with existing external database?

### ISSUE THREAD

**Issue by ahachmann** [nextcloud/helm#125]
Hi, 
Scenario:
I have a running Nextcloud version 17.0.10 on docker. Now I want to move this into kubernetes.
So there is a database with all content of my NC present which I configure in the Helm values.yaml on external database. postgres and mariadb enabled are all set to false, as I do not want such pods to be instantiated.

After installing this, I receive errors from the pod stating it cannot cannot create an admin user in the database. But actually it should not have to as everything is configured in the database already. I am not getting it up with the existing database.

`[hachmann-cloud-nextcloud-f9b86bd6b-w5pm7 nextcloud]  Initializing nextcloud 17.0.10.1 ...
[hachmann-cloud-nextcloud-f9b86bd6b-w5pm7 nextcloud]  Initializing finished
[hachmann-cloud-nextcloud-f9b86bd6b-w5pm7 nextcloud]  New nextcloud instance
[hachmann-cloud-nextcloud-f9b86bd6b-w5pm7 nextcloud]  Installing with MySQL database
[hachmann-cloud-nextcloud-f9b86bd6b-w5pm7 nextcloud]  starting nextcloud installation
[hachmann-cloud-nextcloud-f9b86bd6b-w5pm7 nextcloud]  Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection timed out
[hachmann-cloud-nextcloud-f9b86bd6b-w5pm7 nextcloud]   -> 
[hachmann-cloud-nextcloud-f9b86bd6b-w5pm7 nextcloud]  retrying install...`

When I look into the config.php, I can see that the port is not properly set on port variable, but concatenated to the host. Might work out, but seems to be a little odd. Is that already a problem? Then I would miss the port setting in the values.yaml.

Another approach:
Installing with empty database to have the deployment running and then overwriting that database also does not work, as the database does not get filled and configured with required tables. It seems it is not properly reaching the database. But when I run a simple pod in that namespace, I am able to connect to mysql via mysql command line. So it should not be a network issue.

Any advice would be highly appreciated. I also attached my values.yaml.
[values-blackendPW.txt](https://github.com/nextcloud/helm/files/6783475/values-blackendPW.txt)

**Comment by jessebot** [comment]
Hoi @ahachmann!

I use a configuration similar to this for postgresql, but it shouldn't be too different from mariadb. I missed setting `internalDatabase` to `true` the first time around, so be sure you don't miss it as well:

```yaml
internalDatabase:
  enabled: false
  name: nextcloud

##
## External database configuration
##
externalDatabase:
  enabled: true

  ## Supported database engines: mysql or postgresql
  type: mysql

  ## Database host (you will need to set this to a hostname that can be queried by the nextcloud pod through a kubernetes service or DNS)
  host: db.example.com:5432

  ## Database user
  user: nextcloud

  ## Database password
  password: secretpassword

  ## Database name
  database: nextcloud

  ## Use a existing secret - you can remove the above  4 options in favor of setting the existingSecret.enabled to true
  existingSecret:
    enabled: false
    # secretName: nameofsecret
    # usernameKey: username
    # passwordKey: password
```

This is similar to the stock config in our [values.yaml](https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml#L230), but if that's still giving you issues, could you please post your `values.yaml` after anonymizing sensitive data in it? I'm happy to take a further look :)
