### ISSUE TITLE
Error updating Endpoint Slices for Service nextcloud/nextcloud

### ISSUE THREAD

**Issue by papanito** [nextcloud/helm#14]
The nextcloud pod does not start but eventually fails. I can see this event logged:

```logtalk
8m40s       Warning   FailedToUpdateEndpointSlices   service/nextcloud                Error updating Endpoint Slices for Service nextcloud/nextcloud: Error deleting nextcloud-lv57c EndpointSlice for Service nextcloud/nextcloud: endpointslices.discovery.k8s.io "nextcloud-lv57c" not found
```
The pod itself stuck at
```logtalk
Initializing nextcloud 19.0.0.8 ...
```

# Reproduction steps

Installation using the helm chart and the `values.yml` given below

```bash
helm upgrade nextcloud nextcloud/nextcloud --namespace nextcloud -f nextcloud.values.yml
```

# kubectl version

```yaml
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"archive", BuildDate:"2020-09-03T15:34:56Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

# Values.yml

```yaml
image:
  repository: nextcloud
  tag: 19.0.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prd"
  tls:
    - secretName: nextcloud-tls
      hosts:
        - REDACTED
  labels: {}

nextcloud:
  host: REDACTED
  username: REDACTED
  password: REDACTED
  update: 0
  datadir: /var/www/html/data
  tableprefix:
  defaultConfigs:
    .htaccess: true
    redis.config.php: true
    apache-pretty-urls.config.php: true
    apcu.config.php: true
    apps.config.php: true
    autoconfig.php: true
    smtp.config.php: true

nginx:
  enabled: false
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  config:
    default: true

  resources: {}

internalDatabase:
  enabled: false
  name: nextcloud

externalDatabase:
  enabled: false

mariadb:
  enabled: true
  volumePermissions:
    enabled: true
    securityContext:
      fsGroup: 1001
      runAsUser: 1001
  db:
    name: nextcloud
    user: REDACTED
    password: REDACTED
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
  master:
    persistence:
      accessModes: 
        - ReadWriteOnce
  slave:
    persistence:
      accessModes:
        - ReadWriteOnce
redis:
  enabled: false
  usePassword: false

cronjob:
  enabled: true
  schedule: "*/15 * * * *"
  annotations: {}
  curlInsecure: false
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2
service:
  type: ClusterIP
  port: 8080
  loadBalancerIP: nil

persistence:
  enabled: true
  storageClass: "kadalu.replica3"
  accessMode: ReadWriteOnce
  size: 500Gi

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
```

# Additional info

Interestingly is also, that I only see one `mariadb`-pod where I would expect a master and a slave according to my initial tries, using the helm chart from the previous repo
```logtalk
nextcloud-1599540300-bvnmc   0/1     Error              0          8m35s
nextcloud-1599540300-jhskn   0/1     Error              0          7m53s
nextcloud-1599540300-k7qjq   0/1     Error              0          2m41s
nextcloud-1599540300-kzpds   0/1     Error              0          6m41s
nextcloud-1599540300-smvxj   0/1     Error              0          7m42s
nextcloud-1599540300-tnwgf   0/1     Error              0          7m22s
nextcloud-75fff49d4c-pcc2z   0/1     CrashLoopBackOff   5          15m
nextcloud-mariadb-0          1/1     Running            0          19h
```

```console
$ kubectl -n nextcloud get pvc
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
nextcloud-nextcloud   Bound    pvc-bd1cc26a-c959-422a-a49e-02714da099ef   500Gi      RWO            kadalu.replica3   19h
```
