### ISSUE TITLE
ldaps, where to specify certificate of CA so that I can use ldaps, kubernetes secret?

### ISSUE THREAD

**Issue by lknite** [nextcloud/helm#153]

**Comment by lknite** [comment]
There is no option to do this, the solution requires a manual intervention of the following steps:

Copy the public certificate of the local certificate authority:
```
k cp <path_to_public_ca>/ca.crt <nextcloud_pod>:/usr/local/share/ca-certificates/ca.crt
```

Update the certificate repository with the new cert:
```
update-ca-certificates
```

Now you can configure ldaps via the gui:
```
you must specify:  'ldaps://<server>' in order to specify 636
```

**Comment by lknite** [comment]
Additional note, using the existing helm chart the certificate can be added in this way using the values.yaml file:

```
nextcloud:
  extraVolumes:
  - name: certs
    configMap:
      name: ca-certs
      items:
      - key: "ca.crt"
        path: "ca.crt"
  extraVolumeMounts:
  - name: certs
    mountPath: /usr/local/share/ca-certificates

lifecycle:
  postStartCommand:
  - update-ca-certificates
```

Just need to create a configMap with the certificate added like so:
```
k create configmap ca-certs --from-file=ca.crt=/path_to_ca_cert/ca.crt
```
