### ISSUE TITLE
GCE Ingress only supports "ImplementationSpecific" as path type

### ISSUE THREAD

**Issue by zumbrunnen** [nextcloud/helm#158]
# Problem

When using a [GCE/GKE Ingress](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress) on GCP and using values like these:

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: nextcloud
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: nextcloud
    networking.gke.io/v1beta1.FrontendConfig: nextcloud-frontend-config
```
the deployment of the ingress fails with this error:

```
Translation failed: invalid ingress spec: only "ImplementationSpecific" path type is supported
```

# Possible Solutions

- :3rd_place_medal: Setting `ingress.enabled: false` and provision the ingress on your own. But this makes the `CronJob` fail because of "untrusted domain" issues as the CronJob then calls the service directly (https://github.com/nextcloud/helm/blob/master/charts/nextcloud/templates/cronjob.yaml#L59). So, you have to switch to AJAX cronjobs. That's my workaround right now.
- :1st_place_medal: Somehow magically detect that a GCE ingress is going to be used and set `pathType` to `ImplementationSpecific`.
- :1st_place_medal: Provide an option for the Helm values to specify the desired `pathType`.
