### ISSUE TITLE
CronJob should curl service name rather than ingress host

### ISSUE THREAD

**Issue by elonzh** [nextcloud/helm#16]
Current template:

https://github.com/nextcloud/helm/blob/1cb0e7a2d3788d754c4469d227a8d5d7d9acf5d9/charts/nextcloud/templates/cronjob.yaml#L45-L56

The problems:

1. the cronjob requests an external url, which may not exist if we did not enable ingress
2. even we enable ingress, the ingress may use other ports rather than normal http port(80) or https port(443) 
3. even we use normal http(s) ports, the `.Values.ingress.tls` is not the only approach to set https

The solution:

just curl the service name and service port, like this:

```yaml
              command: [ "curl" ]
              args:
                - "--fail"
                - "-L"
                - "http://{{ template "nextcloud.fullname" . }}:{{ .Values.service.port }}/cron.php"
```

if we use this solution, `.Values.cronjob.curlInsecure ` can be removed.

The test:

![image](https://user-images.githubusercontent.com/8749411/93196294-cf0d9280-f77c-11ea-92f7-66e3e258acc4.png)
