### ISSUE TITLE
Helm Install fails when trying to install Mariadb

### ISSUE THREAD

**Issue by mikeyGlitz** [nextcloud/helm#162]
Values.yml

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 2g
  tls:
    - hosts:
      - files.haus.net
      secretName: nextcloud-app-tls
nextcloud:
  host: files.haus.net
  username: vault:secret/data/nextcloud/app/credentials#app_user
  password: vault:secret/data/nextcloud/app/credentials#app_password
  configs:
    oidc.config.pip: |
      <?php
        $CONFIG = array(
          'oidc_provider_url' => 'https://auth.haus.net/auth/realms/hausnet',
          'oidc_login_client_id' => 'files-portal',
          'oidc_login_client_secret' => '${client_secret}',
          'oidc_login_button_text' => 'Home Network SSO',
          'oidc_login_scope' => 'openid profile',
          'mode' => 'userid',
          'oidc_login_tls_verify' => false,
        );
persistence:
  enabled: yes
  storageClass: nfs-client
  size: 2Ti
  accessMode: ReadWriteMany
podAnnotations:
  vault.security.banzaicloud.io/vault-addr: https://vault.vault-system:8200
  vault.security.banzaicloud.io/vault-tls-secret: vault-cert-tls
  vault.security.banzaicloud.io/vault-role: files
internalDatabase:
  enabled: no
mariadb:
  enabled: yes
  auth:
    database: nextcloud
    username: vault:secret/data/nextcloud/db/credentials#db_user
    password: vault:secret/data/nextcloud/db/credentials#db_password
    architecture: standalone
  primary:
    persistence:
      storageClass: nfs-client
    podAnnotations:
      vault.security.banzaicloud.io/vault-addr: https://vault.vault-system:8200
      vault.security.banzaicloud.io/vault-tls-secret: vault-cert-tls
      vault.security.banzaicloud.io/vault-role: files
redis:
  enabled: yes
  usePassword: yes
  password: ${redisPassword}
rbac:
  enabled: yes
  serviceaccount:
    create: yes
    name: nextcloud
livelinessProbe:
  enabled: no
readinessProbe:
  enabled: no
```

When running the helm chart through Terraform, I end up with the following error:

```
fatal: [192.168.0.120]: FAILED! => {"changed": false, "cmd": "/usr/bin/terraform apply -no-color -input=false -auto-approve=true -lock=true plan.out", "msg": "\nError: template: nextcloud/templates/deployment.yaml:75:66: executing \"nextcloud/templates/deployment.yaml\" at <.Subcharts.mariadb>: nil pointer evaluating interface {}.mariadb\n\n  on files.tf line 47, in resource \"helm_release\" \"rel_files_cloud\":\n  47: resource \"helm_release\" \"rel_files_cloud\" {", "rc": 1, "stderr": "\nError: template: nextcloud/templates/deployment.yaml:75:66: executing \"nextcloud/templates/deployment.yaml\" at <.Subcharts.mariadb>: nil pointer evaluating interface {}.mariadb\n\n  on files.tf line 47, in resource \"helm_release\" \"rel_files_cloud\":\n  47: resource \"helm_release\" \"rel_files_cloud\" {\n\n\n", "stderr_lines": ["", "Error: template: nextcloud/templates/deployment.yaml:75:66: executing \"nextcloud/templates/deployment.yaml\" at <.Subcharts.mariadb>: nil pointer evaluating interface {}.mariadb", "", "  on files.tf line 47, in resource \"helm_release\" \"rel_files_cloud\":", "  47: resource \"helm_release\" \"rel_files_cloud\" {", "", ""], "stdout": "vault_generic_secret.sec_db_creds: Modifying... [id=secret/nextcloud/db/credentials]\nvault_generic_secret.sec_db_creds: Modifications complete after 0s [id=secret/nextcloud/db/credentials]\nhelm_release.rel_files_cloud: Creating...\n", "stdout_lines": ["vault_generic_secret.sec_db_creds: Modifying... [id=secret/nextcloud/db/credentials]", "vault_generic_secret.sec_db_creds: Modifications complete after 0s [id=secret/nextcloud/db/credentials]", "helm_release.rel_files_cloud: Creating..."]}
```

Mariadb was workingin previous versions of the helm chart
