### ISSUE TITLE
Wait helm template failed. nil pointer evaluating interface {}.mariadb

### ISSUE THREAD

**Issue by jgallucci32** [nextcloud/helm#163]
When deploying the latest 2.9.0 and 2.9.1 templates using MariaDB, the following error is displayed:
```
Wait helm template failed. Error: template: nextcloud/templates/deployment.yaml:75:66: executing "nextcloud/templates/deployment.yaml" at <.Subcharts.mariadb>: nil pointer evaluating interface {}.mariadb Use --debug flag to render out invalid YAML : exit status 1
```
There was a recent change in https://github.com/nextcloud/helm/commit/d4fbd2a5ed0b41451191c9c425debee6fa0b1957 to use `.Subcharts.mariadb` as the value for the MYSQL_HOST variable, but this is not defined anywhere nor mentioned anywhere in the instructions (it is also the only reference to `Subcharts` in the entire helm chart)

Here is an example `answers.yaml` to reproduce the problem
```yaml
  internalDatabase:
    enabled: false
  mariadb:
    auth:
      rootPassword: "secretpassword"
    enabled: true
  nextcloud:
    host: "nextcloud.domain.local"
```
