### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by Brice187** [nextcloud/helm#168]
Can not get postgresql to work with this chart.
Can someone provide a minimal example **values.yaml**?

**Comment by tvories** [comment]
You can see my setup here that includes postgres config:

https://github.com/tvories/k8s-gitops/blob/main/cluster/apps/home/nextcloud/helm-release.yaml

**Comment by Brice187** [comment]
okay, so you are storing you `*config.php` on the pvc instead of configuring it in the helm-chart?

**Comment by tvories** [comment]
Yes, mostly because I copied over my setup from an older deployment so I had the config.php already setup in there.

**Comment by jessebot** [comment]
For any current users looking for help, you can check out the [Database Configuration section](https://github.com/nextcloud/helm/blob/e37c3cc0c40545177d702be2b987d6c2c5e6facc/charts/nextcloud/README.md#database-configurations) of the README.

Here's what I personally do in my values.yaml:
```yaml
# you must set this to false to use postgresql
internalDatabase:
  enabled: false

##
## External database configuration
##
externalDatabase:
  enabled: true

  ## Supported database engines: mysql or postgresql
  type: postgresql

  ## Database host
  host: localhost:5432

  ## Database user only needed if you don't use existingSecret below
  # user: nextcloud

  ## Database password only needed if you don't use existingSecret below
  # password:

  ## Database name
  database: nextcloud

  ## Use a existing secret
  existingSecret:
    enabled: true
    secretName: nextcloud-pgsql-credentials
    usernameKey: username
    passwordKey: nextcloudPassword
```

I'm now going to close this due to inactivity since 2021, and then #227 and #359 being merged. If you still need help with general usage in the current version of the nextcloud helm chart, please start a [discussion](https://github.com/nextcloud/helm/discussions/categories/q-a), and if something is broken (not working as described in the docs/values.yaml), then please submit a [new issue](https://github.com/nextcloud/helm/issues/new?assignees=&labels=&template=issue.md&title=A+descriptive+title+of+the+issue).
