### ISSUE TITLE
Feature request:  Specify CA cert via yaml/secret to allow for LDAPS configuration

### ISSUE THREAD

**Issue by lknite** [nextcloud/helm#177]
If you want to use LDAPS a certificate must be copied to the nextcloud pod and imported, then LDAPS can be configured.

However, if you do this and the pod must be deleted and recreated then this configuration will be lost.

It would be nice to specify the certificate via yaml or via the yaml specifiing a secret containing the certificate.

Manual process documented here:
https://github.com/nextcloud/helm/issues/153

**Comment by lknite** [comment]
Using the existing helm chart the certificate can be added in this way using the values.yaml file:

```
nextcloud:
  extraVolumes:
  - name: certs
    configMap:
      name: ca-certs
      items:
      - key: "ca.crt"
        path: "ca.crt"
  extraVolumeMounts:
  - name: certs
    mountPath: /usr/local/share/ca-certificates

lifecycle:
  postStartCommand:
  - update-ca-certificates
```

Just need to create a configMap with the certificate added like so:
```
k create configmap ca-certs --from-file=ca.crt=/path_to_ca_cert/ca.crt
```

Closing ticket, additional documentation might be nice, but just having this issue to find should be enough for folks to locate this solution.
