### ISSUE TITLE
LoadBalancer Annotations Missing

### ISSUE THREAD

**Issue by stevek-pro** [nextcloud/helm#185]
We urgently need these. 

As a workaround: If I try to alter the template locally and deploy from local sources it complains about postgresql, mariadb, redis missing in charts/

Any ideas?

**Comment by XtraLarge** [comment]
Same problem for me .... I need service annotations to specify the external dns name.
I've tried to set it like:
```
service:
  loadBalancerIP: ''
  nodePort: nil
  port: 80
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nextcloud
```
but the helm chart is not prepared to interpret it. .... Pls add!
