### ISSUE TITLE
After migration from docker Internal Server Error

### ISSUE THREAD

**Issue by Y0ngg4n** [nextcloud/helm#189]
I have migrated my nextcloud instance from postgresql as docker version to kubernetes via helm but now i get 
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

```

I am using this helm values:
```yaml
nextcloud:
  host: "cloud.obco.pro" # Host to reach NextCloud
  username: "Yonggan" # Admin
  password: "secret" # Admin Password

persistence:
  enabled: true # Change to true
  existingClaim: "nextcloud-html-pvc" # Persistent Volume Claim created earlier
  accessMode: ReadWriteMany
  size: 2Gi
  nextcloudData:
    enabled: true
    existingClaim: "nextcloud-data-pvc"
    accessMode: ReadWriteMany
    size: 300Gi

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: kubegres.kubegres
  user: nextcloud
  database: nextcloud
  password: "secret"
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
```
Volumes get bound and the are at the correct places. Database is also accessable and in the logs are only this lines:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.244.0.42. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.244.0.42. Set the 'ServerName' directive globally to suppress this message
[Wed Jan 26 21:39:38.405067 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.51 (Debian) PHP/8.0.15 configured -- resuming normal operations
[Wed Jan 26 21:39:38.406178 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
80.138.213.47 - - [26/Jan/2022:21:42:12 +0000] "GET / HTTP/1.0" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
80.138.213.47 - Yonggan [26/Jan/2022:21:42:15 +0000] "GET /status.php HTTP/1.0" 500 425 "-" "Mozilla/5.0 (Linux) mirall/3.4.1git (Nextcloud, garuda-5.16.2-zen1-1-zen ClientArchitecture: x86_64 OsArchitecture: x86_64)"
80.138.213.47 - - [26/Jan/2022:21:42:17 +0000] "GET / HTTP/1.0" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
80.138.213.47 - - [26/Jan/2022:21:42:18 +0000] "GET / HTTP/1.0" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
80.138.213.47 - - [26/Jan/2022:21:42:18 +0000] "GET / HTTP/1.0" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
80.138.213.47 - - [26/Jan/2022:21:42:18 +0000] "GET / HTTP/1.0" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
80.138.213.47 - - [26/Jan/2022:21:42:19 +0000] "GET / HTTP/1.0" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
80.138.213.47 - - [26/Jan/2022:21:42:19 +0000] "GET / HTTP/1.0" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
80.138.213.47 - - [26/Jan/2022:21:42:19 +0000] "GET / HTTP/1.0" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
80.138.213.47 - - [26/Jan/2022:21:42:19 +0000] "GET / HTTP/1.0" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
80.138.213.47 - Yonggan [26/Jan/2022:21:43:17 +0000] "GET /status.php HTTP/1.0" 500 425 "-" "Mozilla/5.0 (Linux) mirall/3.4.1git (Nextcloud, garuda-5.16.2-zen1-1-zen ClientArchitecture: x86_64 OsArchitecture: x86_64)"
80.138.213.47 - Yonggan [26/Jan/2022:21:44:19 +0000] "GET /status.php HTTP/1.0" 500 425 "-" "Mozilla/5.0 (Linux) mirall/3.4.1git (Nextcloud, garuda-5.16.2-zen1-1-zen ClientArchitecture: x86_64 OsArchitecture: x86_64)"
80.138.213.47 - Yonggan [26/Jan/2022:21:45:21 +0000] "GET /status.php HTTP/1.0" 500 425 "-" "Mozilla/5.0 (Linux) mirall/3.4.1git (Nextcloud, garuda-5.16.2-zen1-1-zen ClientArchitecture: x86_64 OsArchitecture: x86_64)"
80.138.213.47 - Yonggan [26/Jan/2022:21:46:23 +0000] "GET /status.php HTTP/1.0" 500 425 "-" "Mozilla/5.0 (Linux) mirall/3.4.1git (Nextcloud, garuda-5.16.2-zen1-1-zen ClientArchitecture: x86_64 OsArchitecture: x86_64)"
```
