### ISSUE TITLE
Cannot write into "config" directory! Error when enabling persistence

### ISSUE THREAD

**Issue by SeveHo** [nextcloud/helm#199]
Hello, 

when enabling persistence I get the following error: 
```sh
Configuring Redis as session handler
Initializing nextcloud 21.0.4.1 ...
Initializing finished
New nextcloud instance
Installing with SQLite database
starting nextcloud installation
Cannot write into "config" directory!
This can usually be fixed by giving the webserver write access to the config directory
```
Interestingly when using a manually created pvc and providing it via `persistence.existingClaim` I do not get this error. The config for the manual pvc looks like this:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cinder-high-speed
```

The values when using the pvc managed by the chart are looking like this:
```yaml
nextcloud:
    configs:
      custom.config.php: |-
        <?php
        $CONFIG = array (
          'overwriteprotocol' => 'https',
          'overwrite.cli.url' => 'https://<REDACTED>.<REDACTED>.com',
          'loglevel' => '2'
        );

persistence:
  enabled: true
  annotations:
    helm.sh/resource-policy: keep
  storageClass: "csi-cinder-high-speed"
```

Did anyone face the same issue or sees what I am doing wrong?
