### ISSUE TITLE
HPA non-functional due to incorrect LabelSelector

### ISSUE THREAD

**Issue by WojoInc** [nextcloud/helm#22]
# Issue

Nextcloud App pod HPA does not work

# Cause

The HPA is unable to get the CPU requested/usage/limit for the application pods.
![image](https://user-images.githubusercontent.com/4422163/95047642-0f8d6b80-06ac-11eb-954d-a93eb4ebeaab.png)

# Why

The HPA references the `nextcloud` deployment. This deployment does not define a component label. Therefore, if you also deploy the `nextcloud-metrics` deployment, one of the following will happen:

1. Metrics are returned for both the metrics pod and application pod, and are averaged together (if resource requests/limits defined on metrics pod)
2. If no resource requests/limits are defined on the metrics pod, the metrics are returned, but the HPA throws an error, because while the application pod may have resources defined, the metrics pod does not, and the HPA is unable to compute and average requests/limits as a result

# What happens

![image](https://user-images.githubusercontent.com/4422163/95048272-2aacab00-06ad-11eb-8e43-eb5f0f648d86.png)

The metrics server logs do not return an error, but their debug output is helpful in highlighting the issue further. In the above, the HPAs I have deployed for nginx ingress controllers specifically call out the component label in their request. These HPAs are working without issue.

# Suggested Fix

Add `app.kubernetes.io/component: app` to the nextcloud application deployment, and update the spec accordingly:
```yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nextcloud
      app.kubernetes.io/component: app
      app.kubernetes.io/name: nextcloud
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nextcloud
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/component: app
        nextcloud-redis-client: 'true'
```

I am happy to open a PR for this issue if this seems like the correct approach.
