### ISSUE TITLE
ingress deployed but not working (login still redirect to login page)

### ISSUE THREAD

**Issue by ziyi-bear** [nextcloud/helm#231]
https://nextcloud.mlc.app/login
![image](https://user-images.githubusercontent.com/54978757/166208725-e4bf225c-33b1-4354-81f8-a8ea290907c9.png)

then I type the correct user password will direct to https://nextcloud.mlc.app/login?redirect_url=/apps/dashboard/ but the page still shows the same as the login page

![image](https://user-images.githubusercontent.com/54978757/166208872-7efeedf2-01b9-45e7-9f49-b292ef1a6c5c.png)

below are my helm chart values, I have been stuck for a few days, Please help! thanks
```yaml
cronjob:
  enabled: true
  failedJobsHistoryLimit: 5
  schedule: '*/15 * * * *'
  successfulJobsHistoryLimit: 2
image:
  tag: 23.0.3-fpm
ingress:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
  className: public
  enabled: true
  tls:
  - hosts:
    - nextcloud.mlc.app
    secretName: nextcloud-tls
internalDatabase:
  enabled: false
mariadb:
  enabled: false
nextcloud:
  configs:
    extra.config.php: |-
      <?php
      $CONFIG = array (
        'overwriteprotocol' => 'https'
      );
    s3.config.php: |-
      <?php
      $CONFIG = array (
        'objectstore' => array(
          'class' => '\\OC\\Files\\ObjectStore\\S3',
          'arguments' => array(
            'bucket'     => 'nextcloud.primary.storage',
            'autocreate' => true,
            'key'        => 'xxxxxxxxxxxx',
            'secret'     => 'xxxxxxxxxxxxx',
            'hostname'   => 'myminio host',
            'port'       => 9000,
            'region'     => 'us-east-1',
            'use_ssl'    => true,
            // required for some non Amazon S3 implementations
            'use_path_style'=> true
          )
        )
      );
  existingSecret:
    enabled: true
    passwordKey: password
    secretName: nextcloud-init-config
    smtpPasswordKey: smtp_password
    smtpUsernameKey: smtp_username
    usernameKey: username
  host: nextcloud.mlc.app
  mail:
    enabled: false
    fromAddress: XXXXXX@gmail.com
nginx:
  enabled: true
persistence:
  enabled: true
  storageClass: openebs-hostpath
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        database: nextcloud
        password: asdasdasdasd
        postgresPassword: asdasdasdasd
        username: nextcloud
      primary:
        persistence:
          enabled: true
rbac:
  enabled: true
redis:
  auth:
    password: asdaasdasdasda
  enabled: true
```
