### ISSUE TITLE
Double domainname in smtp in email server admin settings

### ISSUE THREAD

**Issue by stevek-pro** [nextcloud/helm#236]
When I'm configuring nextcloud like this:

```
  existingSecret:
    enabled: true
    secretName: mysecret
    usernameKey: username
    passwordKey: password
    smtpUsernameKey: smtp_username
    smtpPasswordKey: smtp_password
  update: 0
  datadir: /var/www/html/data
  persistence:
    subPath:
  mail:
    enabled: true
    fromAddress: no-reply@domain.org
    domain: domain.org
    smtp:
      host: host.org
      secure: ssl
      port: 465
      authtype: LOGIN
      name: name
```

and this in the secret:

`smtp_username=no-reply@domain.org`

I find this in UI of basic settings panel of Next Cloud:

`From address no-reply@domain.org @ domain.org`

If I change this in UI it gets rewritten to original settings after reload. What am I doing wrong, how to fix this behaviour and have `domain.org` only once?
