### ISSUE TITLE
Release notes for chart

### ISSUE THREAD

**Issue by hyperbolic2346** [nextcloud/helm#250]
Am I missing where to find the release notes for the chart? I'm looking to upgrade from 2.14.6 to 3.0.0, but I don't see anything about what has changed and what might break. Are there any configuration differences in these releases?

**Comment by jessebot** [comment]
I don't believe we have release notes right now, but this is something we should be able to automate going into the releases according to this guide:

https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

I can start a PR with a basic starting point for `.github/release.yml`:

```yaml
# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
```

I need to test it, and it wouldn't help with previous releases, but it would at least make it so that going forward, you could look at the associated PRs.

In the meantime, each change should have an associated PR, so you can go to the Pull Requests and sort by recently closed, to get an idea of what's changed . From `2.14.6` to `3.0.0` there's been a lot of changes that could be considered breaking. One of the most notable changes will definitely be the appVersion (which is the nextcloud container version tag), so chart version `2.14.6` used the `23.0.3` nextcloud image tag whereas `3.0.0` uses the `24.0.2` image tag. The current nextcloud image tag in `3.4.3` is `25.0.3`, so that's two major versions.

According to the docker repo README right now, it's recommended to only upgrade one major version at a time, so if your docker containers is version 23, you'd need to first upgrade to 24 (so upgrade to chart version 3.0.0), and then to 25:

https://github.com/nextcloud/docker#update-to-a-newer-version

I'm unsure of specific changes to the helm chart itself that would break anything though, I'm going to recommend taking backups of both your files and database regardless, just in case.

@tvories or @provokateurin is there anything either of you can recall that stands out as having been changed that would need revision from the standpoint of the end user values.yaml from chart version 2.14.6 to 3.0.0 outside of the nextcloud container version? To my knowledge, much of it has been just adding features, but I can't recall if anything moved around to different namespaces of the yaml. I may also just be missing in the github interface how to compare a repo tag to the master branch.
