### ISSUE TITLE
Proper intallation guide through the helm chart

### ISSUE THREAD

**Issue by urbaman** [nextcloud/helm#258]
Hi,

Is there a guide somewhere to the proper installation with the Helm chart, with all of the connections between all the different settings?
Like: how to set external db host if I use the mariadb chart? Is it automatically set?
Do I need the metrics server to be able to use prometheus operator to scrape metrincs?
How to set the different PVCs )or just one PVC) to its proper function (config, data, db, ...)?

Thank you very much,

**Comment by jessebot** [comment]
Hoi!

I don't think there is outside of the [README.md](https://github.com/nextcloud/helm/tree/master/charts/nextcloud#readme), where you can see some notes have been added on how to do a few specific things. We also have https://nextcloud.github.io/helm/ but it looks like it is just the default helm instructions.

@provokateurin can correct me if I'm missing any other documentation. Kate, do you think maybe it's time start adding actual doc pages to the github pages jekyll site? We could start with some of the existing info in the readme for various pages? I'm not sure if there's already been discussion on this or not.

Regardless, we can add more to the README on other specific topics. I'm always for making any project easier to start working with! :) Each topic update can be its own PR, so one for explaining how to use external databases, one for Persistence (to perhaps improve [this section](https://github.com/nextcloud/helm/tree/master/charts/nextcloud#persistence) ), and another for metrics. I think it might also make sense to break up the configuration table into different smaller tables similar to what bitnami does in their READMEs, like for mariadb: [here](https://github.com/bitnami/charts/tree/main/bitnami/mariadb).

To answer some of your questions though:

<details>
  <summary><i>how to set external db host if I use the mariadb chart? Is it automatically set?</i></summary>

To use an external database, you need to set `internalDatabase.enabled` to `false` and  fill in the `externalDatabase` section of the `values.yaml`. Here's an example for postgresql:
 
```yaml
  internalDatabase:
    enabled: false

  # External database configuration
  externalDatabase:
    enabled: true
    ## Supported database engines: mysql or postgresql
    type: postgresql
    # if you use postgresql bundled with our nextcloud chart, you will use localhost:5432.
    # It will be a different port for mariadb
    host: localhost:5432
    # Database name
    database: nextcloud
    ## Use a existing secret for credentials (this is optional)
    existingSecret:
      enabled: true
      secretName:  pgsql-credentials
      usernameKey: username
      passwordKey: nextcloudPassword   
 ```
 
Note that you'd still need to either deploy the postgresql or mariadb chart using our values.yaml (we use the ones hosted by bitnami), or have an already running database instance.

</details>

 <details>
  <summary><i>Do I need the metrics server to be able to use prometheus operator to scrape metrics?</i></summary>
 
You do need to deploy the prometheus operator yourself, and it should be able to get you basic kubernetes metrics about the nextcloud infrastructure, but to get specific metrics on nextcloud itself, such as total shares or total files, you would need to enable the metrics parameter in the `values.yaml` to use [xperimental/nextcloud-exporter](https://github.com/xperimental/nextcloud-exporter):
 
```yaml
## Prometheus Exporter / Metrics
##
metrics:
  enabled: true

  replicaCount: 1
  # The metrics exporter needs to know how you serve Nextcloud either http or https
  https: false
  # Use API token if set, otherwise fall back to password authentication
  # https://github.com/xperimental/nextcloud-exporter#token-authentication
  # Currently you still need to set the token manually in your nextcloud install
  token: ""
  timeout: 5s
  # if set to true, exporter skips certificate verification of Nextcloud server.
  tlsSkipVerify: false

  image:
    repository: xperimental/nextcloud-exporter
    tag: 0.6.0
    pullPolicy: IfNotPresent

  ## Metrics exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  # resources: {}

  ## Metrics exporter pod Annotation and Labels
  # podAnnotations: {}

  # podLabels: {}
 ```
 
 You would also need to supply a server token, which you can read about [here](https://github.com/xperimental/nextcloud-exporter#token-authentication), and then can implement as en existing k8s secret if you chose with these parameters:
 
```yaml
 nextcloud:
  ## Use an existing secret: you have to create this ahead of time
  existingSecret:
    # this is set to false by default
    enabled: true
    tokenKey: serverinfo_token
 ```
 
</details>
 
<details>
  <summary><i>How to set the different PVCs )or just one PVC) to its proper function (config, data, db, ...)?</i></summary>
 
 Persistence for the database is set at the database chart level, so you can check out the database charts for more info, but the gist of it is documented in the values.yaml here starting at this line for mariadb: https://github.com/nextcloud/helm/blob/a491977458b5111cc0afd06386aa63ef46720f4c/charts/nextcloud/values.yaml#L265-L286
 
 more data on the postgresql chart can be found here: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
 more data on the mariadb chart can be found here: https://github.com/bitnami/charts/tree/main/bitnami/mariadb
 
 Persistence for the config and data can be stored either on one PVC or two. If you leave `persistence.nextcloudData.enabled` set to `false` nextcloud will store both the data and configs using the same persistent volume claim, but if you set that parameter to `true` it will store them separately:
 
 https://github.com/nextcloud/helm/blob/a491977458b5111cc0afd06386aa63ef46720f4c/charts/nextcloud/values.yaml#L342-L375
 
</details>
