### ISSUE TITLE
Cannot configure TLS while using MetalLB

### ISSUE THREAD

**Issue by kamilkkonieczka** [nextcloud/helm#28]
I'm trying to install this chart on bare metal cluster at home. It seems to work perfectly fine using MetalLB right now, but the problem is that chart is ignoring my TLS configuration. I understand that using port 80 in load balancer will not work, but pod seems to expose only port 80 anyway.

Please have a look at my values.yml
```
USER-SUPPLIED VALUES:
ingress:
  enabled: true
  hosts:
    - "nextcloud.domain.tld"
  tls:
    - hosts:
        - "nextcloud.domain.tld"
      secretName: wildcard-domain-tld-tls
  path: /
nextcloud:
  host: "nextcloud.domain.tld"
service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: 172.16.100.100
```
