### ISSUE TITLE
ExistingClaim for MariaDB and Postgresql

### ISSUE THREAD

**Issue by andresp** [nextcloud/helm#281]
If my understanding of the DB volumes is correct, the data that is stored is not just a cache or temporary, thus having more control over the volumes would allow for better backup/migration strategies. It would be useful if the database persistence settings in the chart allowed for the specifying an existingClaim, just like for nextcloud(-data) volumes.

**Comment by StephenLasseter** [comment]
Though it doesn't seem to be documented in the values file for the chart, it does indeed appear to be supported.  This chart uses the bitnami charts for mariadb and postgresql, so I think whatever is valid in those can be set.  I just tested the following and it worked:

`helm install nextcloud --set mariadb.enabled=true --set mariadb.primary.persistence.enabled=true --set mariadb.primary.persistence.existingClaim=my-mariadb-pvc -n testns nextcloud/nextcloud
`
```
❯ k get statefulsets.apps nextcloud-mariadb -oyaml | yq '.spec.template.spec.volumes'
- configMap:
    defaultMode: 420
    name: nextcloud-mariadb
  name: config
- name: data
  persistentVolumeClaim:
    claimName: my-mariadb-pvc
```
