### ISSUE TITLE
Nextcloud doesn't pick up Postgresql as external database

### ISSUE THREAD

**Issue by Marcel-Lambacher** [nextcloud/helm#289]
### General
I configured nextcloud to use Postgresql as an external database, however according from the log it isn't picked up and SQLite is still used.

### Configuration
In order to use nextcloud as an external database, I provided the following chart configuration:
```
externalDatabase:
  enabled: true
  type: postgresql
  host: database.postgresql.svc.cluster.local
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-postgresql-auth
    usernameKey: username
    passwordKey: password
```

### Logs
When starting the container, I could identify that SQLite is still used:

```
2022-10-01 20:03:32 | 2022-10-01T20:02:59.39735629+02:00 stdout F Initializing nextcloud 24.0.5.1 ...
2022-10-01 20:03:32 | 2022-10-01T20:03:13.495185169+02:00 stdout F New nextcloud instance
2022-10-01 20:03:32 | 2022-10-01T20:03:13.563862163+02:00 stdout F Installing with SQLite database
2022-10-01 20:03:32 | 2022-10-01T20:03:13.564223986+02:00 stdout F Starting nextcloud installation
2022-10-01 20:03:32 | 2022-10-01T20:03:29.065688989+02:00 stdout F Nextcloud was successfully installed
```
### Additional information
1. Yes the secret exists, I decoded the values and tested the access manually, the user can authenticate and access the database
2. I also use Redis as caching mechanism, does the two interfere?
3. We're talking about a fresh installation and empty PV
4. From what it seams, the redis configuration is quite similar and works
5. Full values.yaml:
<details>
  <summary>Click me</summary>

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: nextcloud-redirect-card-and-cal-dav@kubernetescrd

lifecycle:
  postStartCommand: ["/bin/sh", "-c", "apt update && apt install -y smbclient libsmbclient-dev"]

nextcloud:
  host: domain.de
  existingSecret:
    enabled: true
    secretName: nextcloud-admin-secret
    usernameKey: username
    passwordKey: password

  configs:
    traefik.config.php: |-
      <?php
      $CONFIG = array (
        'overwrite.cli.url' => 'https://domain.de',
        'overwriteprotocol' => 'https'
      );

  extraVolumes:
  - name: nas-storage
    hostPath:
      path: /data
      type: ""

  extraVolumeMounts:
   - name: nas-storage
     mountPath: /nas-storage

persistence:
  enabled: true
  storageClass: longhorn-single-replica

redis:
  global:
    storageClass: longhorn-single-replica
  architecture: standalone
  enabled: true
  auth:
    enabled: true
    existingSecret: nextcloud-redis-auth
    existingSecretPasswordKey: password

externalDatabase:
  enabled: true
  type: postgresql
  host: database.postgresql.svc.cluster.local
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-postgresql-auth
    usernameKey: username
    passwordKey: password
```
</details>
