### ISSUE TITLE
Metrics: skip nextcloud HTTPS TLS check

### ISSUE THREAD

**Issue by kashapovd** [nextcloud/helm#291]
I faced with a problem when I use self-signed certificates and metrics also enabled. The metric exporter just cannot check the authority of the certificate.

I suggest to add an additional option to skip that verifying according to nextcloud-exporter docs. This can be done by passing --tls-skip-verify option to the nextcloud-exporter via NEXTCLOUD_TLS_SKIP_VERIFY env variable. 

Possible implementation might look like this:
```
metrics:
  enabled: true
  https:
    enabled: true
    skipVerify: true
```
I can prepare a PR, thanks.
