### ISSUE TITLE
Nextcloud host not changed

### ISSUE THREAD

**Issue by gizmo15** [nextcloud/helm#295]
Hi,

I use the last version of the helm chart :

Chart.yaml :
```
apiVersion: v2
name: nextcloud
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

dependencies:
  - name: nextcloud
    version: 3.1.2
    repository: https://nextcloud.github.io/helm/

```

In the values.yaml :
```
nextcloud:
  replicaCount: 1
  ingress:
    enabled: true
    annotations: {}
    className: nginx-internal
    path: /
    hosts:
      - nextcloud.kubetest.fr.work.net
  nextcloud:
    host: nextcloud.kubetest.fr.work.net
    username: admin
    password: changeme
  internalDatabase:
    enabled: true
    name: nextcloud
  redis:
    enabled: true
    architecture: standalone
    master:
      persistence:
        enabled: true
        storageClass: "openebs-lvm"
        size: 2Gi
  persistence:
    # Nextcloud Data (/var/www/html)
    enabled: true
    annotations: {}
    storageClass: "openebs-lvm"
    accessMode: ReadWriteOnce
    size: 1Gi
```

But the health check is always KO :
```
curl -vv -H 'Host: nextcloud.kubetest.fr.work.net' http://127.0.0.1/status.php

< HTTP/1.1 400 Bad Request

{"error": "Trusted domain error.", "code": 15}
```

But if i specified the default value, the check is OK :
```
curl -vv -H 'Host: nextcloud.kube.home' http://127.0.0.1/status.php

< HTTP/1.1 200 OK

{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"24.0.5.1","versionstring":"24.0.5","edition":"","productname":"Nextcloud","extendedSupport":false}
```

Is my values.yaml is wrong or i need to modify something else?

thanks!
