### ISSUE TITLE
Override Redis with External Server

### ISSUE THREAD

**Issue by joepa37** [nextcloud/helm#305]
How to configure an External Redis Server as the [externalDatabase](https://github.com/nextcloud/helm/blob/c630372155aca576fa1c3e2d7bcd19a2ee18566c/charts/nextcloud/values.yaml#L214) 
https://github.com/nextcloud/helm/blob/c630372155aca576fa1c3e2d7bcd19a2ee18566c/charts/nextcloud/values.yaml#L214
parameter in `values.yaml` or at least how to override the [redis.config.php](https://github.com/nextcloud/helm/blob/c630372155aca576fa1c3e2d7bcd19a2ee18566c/charts/nextcloud/templates/config.yaml#L33-L45) https://github.com/nextcloud/helm/blob/c630372155aca576fa1c3e2d7bcd19a2ee18566c/charts/nextcloud/templates/config.yaml#L33-L45 to manually override the redis host, port and password? Is this posible?

**Comment by joepa37** [comment]
Solved adding this configuration:

 ```yaml
 phpConfigs:
    redis-cluster.ini: |-
      session.save_handler = rediscluster
      session.save_path = "seed[]=redis.production.svc:6379&timeout=2&read_timeout=2&failover=error&persistent=1&auth=your-redis-password"
```

```yaml
redis-cluster.config.php: |-
      <?php
      $CONFIG = [
        'memcache.local' => '\\OC\\Memcache\\Redis',
        'memcache.distributed' => '\\OC\\Memcache\\Redis',
        'memcache.locking' => '\\OC\\Memcache\\Redis',
        'redis.cluster' => [
          'seeds' => [
            'redis.production.svc:6379',
          ],
          'timeout' => 0.0,
          'read_timeout' => 0.0,
          'failover_mode' => \RedisCluster::FAILOVER_ERROR,
          'password' => 'your-redis-password'
        ],
      ];
```
