### ISSUE TITLE
Postgresql-HA oc_admin pool_passwd issue

### ISSUE THREAD

**Issue by joepa37** [nextcloud/helm#308]
I have this issue when creating an instance with postgresql-ha cluster

```
Next OC\DB\Exceptions\DbalException: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] FATAL: md5 authentication failed
--
Wed, Nov 2 2022 12:51:40 am | DETAIL: pool_passwd file does not contain an entry for "oc_admin" in /var/www/html/lib/private/DB/Exceptions/DbalException.php:71
```

Since pgpool requires to specify a list of users and passwords in the `pool_passwd` file; For some reason, the nextcloud installation process internally creates an `oc_admin` user, but pgpool won't recognize it until it is added to this pool_passwd file with the password the user was created with.

Everything seems to work fine with the mariadb-galera cluster; so this is an issue only for postgresql-ha cluster.

**Comment by jessebot** [comment]
I haven't tried spinning up nextcloud with an HA postgresql cluster yet, but could you post the database/postgresql sections of your values.yaml? This is my current postgres config in my values.yaml:

```yaml
# Uses: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          username: nextcloud
          database: nextcloud
          existingSecret: nextcloud-pgsql-credentials
          secretKeys:
            userPasswordKey: nextcloudPassword
            adminPasswordKey: postgresPassword
    volumePermissions:
      enabled: true
    primary:
      podAnnotations:
        k8up.io/backupcommand: "sh -c 'PGDATABASE=\"$POSTGRES_DB\" PGUSER=\"$POSTGRES_USER\" PGPASSWORD=\"$POSTGRES_PASSWORD\" pg_dump --clean'"
        k8up.io/file-extension: .sql
      pgHbaConfiguration: |-
        local all all trust
        host all all 127.0.0.1/32 md5
        host all nextcloud 10.0.0.0/8 md5
      initdb:
        scripts:
          my_init_script.sql: |
            ALTER DATABASE nextcloud OWNER TO nextcloud;
            GRANT ALL PRIVILEGES ON DATABASE nextcloud TO nextcloud;
            GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nextcloud;
      persistence:
        enabled: true
        # storageClass: "standard"
        existingClaim: nextcloud-postgresql
```

Perhaps we should include something in the init_script or an initContainer that updates this pool_passwd file? Open to suggestions and collaboration on this :)
