### ISSUE TITLE
Deploying helm chart refuses to start

### ISSUE THREAD

**Issue by 2fst4u** [nextcloud/helm#328]
My values are as follows:

```
values:
    ## Official nextcloud image version
    ## ref: https://hub.docker.com/r/library/nextcloud/tags/
    ##
    image:
      repository: nextcloud
      # tag: 24.0.3-apache
      pullPolicy: IfNotPresent
      # pullSecrets:
      #   - myRegistrKeySecretName

    nameOverride: ""
    fullnameOverride: ""
    podAnnotations: {}
    deploymentAnnotations: {}

    # Number of replicas to be deployed
    replicaCount: 1



    nextcloud:
      host: [my actual host]
      username: admin
      password: changeme
      ## Use an existing secret
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: adminusername
        passwordKey: adminpassword
        # tokenKey: serverinfo_token
        smtpUsernameKey: smtp_username
        smtpPasswordKey: smtp_password
      update: 0
      # If web server is not binding default port, you can define it
      containerPort: 8080
      datadir: /var/www/html/data
      persistence:
        subPath:
      mail:
        enabled: false
        # fromAddress: nextcloud
        domain: smtp.gmail.com
        smtp:
          host: smtp.gmail.com
          secure: ssl
          port: 587
          authtype: LOGIN
          # name: user
          # password: pass


      # Extra mounts for the pods. Example shown is for connecting a legacy NFS volume
      # to NextCloud pods in Kubernetes. This can then be configured in External Storage
      extraVolumes:
       - name: shared
         nfs:
          server: storage
          path: /mnt/Volume01/Shared
      extraVolumeMounts:
       - name: shared
         mountPath: "/shared"
    

    internalDatabase:
      enabled: false
      name: nextcloud


    ##
    ## External database configuration
    ##
    externalDatabase:
      enabled: true

      ## Supported database engines: mysql or postgresql
      type: postgresql

      ## Database host
      host: postgres-service:5432

      ## Database user
      # user: postgres

      ## Database password
      password:

      ## Database name
      database: postgres

      ## Use a existing secret
      existingSecret:
        enabled: true
        secretName: postgres-secret
        usernameKey: POSTGRES_USER
        passwordKey: POSTGRES_PASSWORD


    ## Cronjob to execute Nextcloud background tasks
    ## ref: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron
    ##
    cronjob:
      enabled: true


    service:
      type: ClusterIP
      port: 8080
      loadBalancerIP: nil
      nodePort: nil

    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      # Nextcloud Data (/var/www/html)
      enabled: true
      annotations: {}
      ## nextcloud data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      storageClass: "managed-nfs-storage"

      ## A manually managed Persistent Volume and Claim
      ## Requires persistence.enabled: true
      ## If defined, PVC must be created manually before volume will be bound
      # existingClaim:

      accessMode: ReadWriteOnce
      size: 8Gi

      ## Use an additional pvc for the data directory rather than a subpath of the default PVC
      ## Useful to store data on a different storageClass (e.g. on slower disks)
      nextcloudData:
        enabled: false
        subPath:
        annotations: {}
        # storageClass: "-"
        # existingClaim:
        accessMode: ReadWriteOnce
        size: 8Gi

    resources: # {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      limits:
        # cpu: 1000m
        memory: 1500Mi
      requests:
       cpu: 1000m
       memory: 1000Mi

    ## Liveness and readiness probe values
    ## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
    ##
    livenessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    startupProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1
```

I receive the following output in shell in the container:

`Initializing nextcloud 25.0.2.3 ...`

Followed by:

```
New nextcloud instance
Installing with PostgreSQL database
Starting nextcloud installation
Console has to be executed with the user that owns the file config/config.php
Current user id: 33
Owner id of config.php: 0
Try adding 'sudo -u #0' to the beginning of the command (without the single quotes)
If running with 'docker exec' try adding the option '-u 0' to the docker command (without the single quotes)
Retrying install...
```

Over and over. Then after a while the container is killed, restarts and just says:

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.2.14. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.2.14. Set the 'ServerName' directive globally to suppress this message
[Tue Dec 27 01:49:55.385150 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.1.13 configured -- resuming normal operations
[Tue Dec 27 01:49:55.385313 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

And just sits there doing nothing. The container doesn't properly start, just the cron container keeps running. I can't find anyone with this issue online so it must be something I'm doing wrong but I have no idea what. Any ideas?
