### ISSUE TITLE
Values.image parameters not honored by helm chart in ArgoCD

### ISSUE THREAD

**Issue by jessebot** [nextcloud/helm#336]
With chart version: `3.4.1` I can only get the parameters under `image` to work if I put them under `nextcloud` in my `values.yaml`. As an example, I would like to use the 25.0.3-fpm `image.tag`.

This is from the current `values.yaml` in this repo and if I use it, but just change the tag, it does not honor the tag I have specified:

```yaml
image:
  repository: nextcloud
  tag: 25.0.3-fpm
  pullPolicy: IfNotPresent
```

and it produces this (with `helm template nextcloud .` from the directory where I have a `Chart.yaml` that just references the current nextcloud chart version and a values.yaml):

<details>
  <summary>Wrong output rendered template</summary>

```yaml
# Source: nextcloud/charts/nextcloud/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-3.4.1
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: nextcloud
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: nextcloud
        app.kubernetes.io/component: app
      annotations:
        nextcloud-config-hash: a5aae02b1b8278a9c8a2dc143e82d3737fc295f62c34afd617207f37d1b2b438
        php-config-hash: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:25.0.3-apache
        imagePullPolicy: IfNotPresent
...
```

</details>

If I change my local values.yaml to put `image.tag` under `nextcloud` it succeeds in the way I would expect:

```yaml
nextcloud:
  image:
    repository: nextcloud
    tag: 25.0.3-fpm
    pullPolicy: IfNotPresent
```

And produces this when I run `helm template`:

<details>
  <summary>Correct expected template rendered output</summary>

```yaml
# Source: nextcloud/charts/nextcloud/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-3.4.1
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: nextcloud
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: nextcloud
        app.kubernetes.io/component: app
      annotations:
        nextcloud-config-hash: a5aae02b1b8278a9c8a2dc143e82d3737fc295f62c34afd617207f37d1b2b438
        php-config-hash: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:25.0.3-fpm
        imagePullPolicy: IfNotPresent
```

</details>

This could be because we're only looking for `nextcloud.image` in the deployment.yaml template:

https://github.com/nextcloud/helm/blob/315313be6f6c14badeb07fad43ddd1e3f983e7fd/charts/nextcloud/templates/deployment.yaml#L48-L58

Perhaps something is not working here:

https://github.com/nextcloud/helm/blob/315313be6f6c14badeb07fad43ddd1e3f983e7fd/charts/nextcloud/templates/_helpers.tpl#L42-L51

If I clone this repo, and cd into `charts/nexcloud`, update the `values.yaml` parameter `image.tag` to `25.0.3-fpm`, then run `helm template nextcloud .` from that directory, the resulting rendered manifests are correct, so I think the `_helpers.tpl` only applies to the base template and does not take into account additional values.yaml passed in by end users.

**Comment by jessebot** [comment]
Not sure if this is related to #112 or not, but still refining the backlog to research if others are having this issue.

**Comment by provokateurin** [comment]
I don't think it's related

**Comment by jessebot** [comment]
I'm still having this problem with the latest version of the helm chart.

I think a solution could be to changed this line here:
https://github.com/nextcloud/helm/blob/aa54644c00638a2b93d51a2bd9cd75bee5a04b73/charts/nextcloud/templates/deployment.yaml#L57

to be something like this in `charts/nextcloud/templates/deployment.yaml`:

```yaml
     {{- if .Values.image.tag }}
     image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
     {{ else }}
     image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}-{{( .Values.image.flavor }} 
     {{- end }}
```

And then we remove the stuff about this in `_helpers.tpl` and update `values.yaml` to actually specify the `image.flavor` by default? Creating a draft PR, https://github.com/nextcloud/helm/pull/375, to show what I mean.

**Comment by jessebot** [comment]
Closed the draft PR as I've just realized this is only happening through Argo CD for some reason 😨 This issue doesn't occur when I just use k3s with helm directly. I'll report in more as I figure out what the issue is!

**Comment by jessebot** [comment]
So, this happens if you were using argocd the old way, before they introduced the beta multiple sources feature. Here's an example of how it was broken before. You could previously only use the values.yaml in the source helm chart repo, so the only way to use _your own_ values.yaml was to have a repo where you created a helm chart like [this](https://gitlab.com/vleermuis_tech/goobernetes/nextcloud/-/tree/c376d32e6ac13d033c7537638e5fb3d1f422b006/helm):

-`Chart.yaml`:
```yaml
---
apiVersion: v2
version: 0.1.0
name: nextcloud
dependencies:
  - name: nextcloud
    repository: https://nextcloud.github.io/helm/
    version: 3.4.1
```

With the above `Chart.yaml`, the only way to get the `values.yaml` to work was to do this:

```yaml
nextcloud:
  image:
    repository: nextcloud
    tag: 25.0.3-fpm
```

This is the [argo manifest](https://gitlab.com/vleermuis_tech/goobernetes/nextcloud/-/blob/c376d32e6ac13d033c7537638e5fb3d1f422b006/nextcloud_argocd_template.yaml#L1-L27) I was using:
```yaml
---
# webapp is deployed LAST because we need secrets and persistent volumes up 1st
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-web-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nextcloud
  source:
    # helm repo
    repoURL: https://gitlab.com/vleermuis_tech/goobernetes/nextcloud.git
    path: helm/
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      prune: true
      selfHeal: true
```

Now with the Argo CD app version `2.6.x`, you can do the following to use a different source for your `values.yaml` than the source with the actual helm chart like [this](https://gitlab.com/vleermuis_tech/goobernetes/nextcloud/-/blob/c937920655de781b1843a02fc92e83c9764d227a/nextcloud_argocd_template.yaml#L1-L32):

```yaml
---
# webapp is deployed LAST because we need secrets and persistent volumes up 1st
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-minimal-web-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nextcloud
  sources:
    # official nextcloud helm repo
    - repoURL: 'https://nextcloud.github.io/helm'
      chart: nextcloud
      targetRevision: 3.5.7
      helm:
        valueFiles:
        - $values/values.yaml
    # our values.yaml file locally
    - repoURL: 'https://gitlab.com/vleermuis_tech/goobernetes/nextcloud.git'
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
```

This solves the problem entirely, but [since this is a beta feature](https://argo-cd.readthedocs.io/en/release-2.6/user-guide/multiple_sources/), it might break again 🙃 :
<img width="719" alt="Screenshot 2023-04-15 at 15 31 12" src="https://user-images.githubusercontent.com/2389292/232227003-b0207276-0eeb-4686-9fd0-374539ebf5cc.png">

Closing as this is fixed in my testing with Argo CD helm chart version `5.28.1` using the nextcloud helm chart version `3.5.7` though :)
