### ISSUE TITLE
Feature: existingSecret for redis and mariadb deployment

### ISSUE THREAD

**Issue by aov-arnold** [nextcloud/helm#350]
## Description of the change

Introduce an existingSecret option in the values.yaml for mariadb and redis deployment. The used bitnami charts support that. 

- It should be also possible that nextcloud uses this secret to authenticate to redis. Currently I cannot see any option to configure the redis passwort on the nextcloud side apart from the nextcloud.configs way.
- For the mariadb authentication this should be already configurable in the externalDatabase section.

## Benefits

No secrets in the yamls. Especially important when deploying via GitOps. For example the flux HelmRelease CRD manifest in the git repository should never contain secrets.

**Comment by aov-arnold** [comment]
Or do you know any other way to avoid secrets in the manifests?

**Comment by jessebot** [comment]
That seems like a fine idea. :) If you submit a PR for this, we can review it.

**Comment by aov-arnold** [comment]
I'm not yet a helm expert but I will look into it :) 

In the meantime I've found [valuesFrom](https://fluxcd.io/flux/components/helm/helmreleases/#values-overrides) in the HelmRelease CRD which seems to be a workaround. It allows to inject values from a ConfigMap or Secret into the helm values.

**Comment by jessebot** [comment]
Awesome, and no problem :) It might make sense to also include your findings on `valuesFrom` in the [README](https://github.com/nextcloud/helm/blob/0c62c6b544cd7dd6bfb29565f8e75346fac8b7a1/charts/nextcloud/README.md) somewhere, to help others who find this with other values.

If you decide to do the change, it should just be adding the values you see in the other chart, to our values.yaml for mariadb somewhere around here:
https://github.com/nextcloud/helm/blob/0c62c6b544cd7dd6bfb29565f8e75346fac8b7a1/charts/nextcloud/values.yaml#L266-L274

And updating the parameters in our readme here:
https://github.com/nextcloud/helm/blob/0c62c6b544cd7dd6bfb29565f8e75346fac8b7a1/charts/nextcloud/README.md?plain=1#L128-L134

And for redis, around here:
https://github.com/nextcloud/helm/blob/0c62c6b544cd7dd6bfb29565f8e75346fac8b7a1/charts/nextcloud/values.yaml#L313-L317

And updating the readme to add the new parameters around here:
https://github.com/nextcloud/helm/blob/0c62c6b544cd7dd6bfb29565f8e75346fac8b7a1/charts/nextcloud/README.md?plain=1#L141-L143

**Comment by jessebot** [comment]
The work for this has been in #359. Just waiting on a review.

**Comment by NislAr98** [comment]
Does it configure the passwords in the redis/mariadb/postgresql container as well as on the nextcloud-side?

**Comment by jessebot** [comment]
Yes, except for databases, you still currently need to also set `internalDatabase.enabled` to false, and then you need to fill out the `externalDatabase` params in your values.yaml like this for example:

```yaml
internalDatabase:
  enabled: false

##
## External database configuration
##
externalDatabase:
  enabled: true

  ## Supported database engines: mysql or postgresql
  type: postgresql

  ## Database host (plus port)
  host: postgres:5432

  ## Database user
  user: nextcloud

  ## Database name
  database: nextcloud

  ## Use a existing secret
  existingSecret:
    enabled: true
    secretName: nameofsecret
    usernameKey: db-username
    passwordKey: db-password
    
## PostgreSQL chart configuration
## for more options see https://github.com/bitnami/charts/tree/main/bitnami/postgresql
##
postgresql:
  enabled: false
  global:
    postgresql:
      # global.postgresql.auth overrides postgresql.auth
      auth:
        # username: nextcloud
        # password: changeme
        database: nextcloud
        # Name of existing secret to use for PostgreSQL credentials.
        # auth.postgresPassword, auth.password, and auth.replicationPassword will be ignored and picked up from this secret.
        # secret might also contains the key ldap-password if LDAP is enabled.
        # ldap.bind_password will be ignored and picked from this secret in this case.
        existingSecret: "mycoolsecret"
        # Names of keys in existing secret to use for PostgreSQL credentials
        secretKeys:
          adminPasswordKey: "somepasskey"
          userPasswordKey: "someuserkey"
          # replicationPasswordKey: "somekey"
```
