### ISSUE TITLE
changing containerPort doesn't affect apache

### ISSUE THREAD

**Issue by hobyte** [nextcloud/helm#363]
## Describe your Issue
setting `nextcloud.containerPort` value doesn't change the Port apache httpd is listening to. it only changes the container Port in the deployment yaml, while the apache config still uses Port 80

### Logs and Errors

nextcloud pod logs:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.244.0.103. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
```

## Describe your Environment

- Kubernetes distribution:  talos v1.2.7, kubernetes 1.26.0
- storage class: hetzner storagebox mounted with [smb storage class](https://github.com/kubernetes-csi/csi-driver-smb).

- Helm Version (or App that manages helm):  helm version 3.11.2

- Helm Chart Version:  3.5.3

- `values.yaml`:

```yaml
nextcloud:
  host: cloud.example.com
  configs:
    custom.config.php: |-
      <?php
      $CONFIG = array (
        'overwriteprotocol' => 'https',
        'overwrite.cli.url' => 'https://cloud.example.com',
        'filelocking.enabled' => 'true',
        'loglevel' => '0',
        'enable_previews' => false
      );
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
  containerPort: 8080
replicaCount: 1
internalDatabase:
  enabled: false
mariadb:
  enabled: true
  primary:
    persistence:
      enabled: true
persistence:
  enabled: true
readinessProbe:
  enabled: false
livenessProbe:
  enabled: false
```

## Additional context, if any

I use a hetzner storage box for my kubernetes storage. It's mounted with a [smb storage class](https://github.com/kubernetes-csi/csi-driver-smb). This is my storageClass definition:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storagebox
  namespace: storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: smb.csi.k8s.io
parameters:
  source: "//xyz.your-storagebox.de/xyz"
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "storage"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "storage"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - cache=loose
  - actimeo=30
  - noserverino
```
Due to permission issues, User and UserGroup are set tp 1001 in nextcloud. I don't think the storage class itself is the issue, but the container port, that isn't configured completly

**Comment by Mx7ca** [comment]
I'm currently trying to set the user to 33 (www-data) and I encounter the same problem.

If I understand it correctly, the problem is that the docker-image per default uses Port 80 for Apache2 which seems not to be configurable via Kubernetes. According to https://github.com/nextcloud/helm/pull/98#issuecomment-844551455, it should be possible to use an FPM image in combination with nginx, but even if one could get the webserver listen to something different than port 80, I think the static `targetPort` in https://github.com/nextcloud/helm/blob/23a180f8e9698da3f455b7432583abea4634d2d8/charts/nextcloud/templates/service.yaml#L18 would cause problems.

**Comment by jessebot** [comment]
I've just merged this PR, which might help:
https://github.com/nextcloud/helm/commit/a215de8e0cafd940818b888e94806a387500abc4

**Comment by jessebot** [comment]
Could you try again and see if the issue persists with helm chart version `3.5.12`?

**Comment by jacksgt** [comment]
Hi @jessebot , 
thanks for your work, unfortunately this does not fix the issue.
The problem is that *Apache* is configured to listen on port 80 (which cannot be changed):

```
$ kubectl exec -it deploy/nextcloud -- cat /etc/apache2/sites-enabled/000-default.conf 
<VirtualHost *:80>
...
```

**Comment by jessebot** [comment]
Sorry, been busy at work! I don't actually use the apache flavor of the docker tag, but let me poke around https://github.com/nextcloud/docker and see if anything jumps out at me :)

**Comment by jessebot** [comment]
I think to accommodate this, we'd need to have this be configurable in the [apache docker container](https://github.com/nextcloud/docker/blob/master/27/apache/Dockerfile) 🤔

@georglauterbach can you post an example of what you did? Is it just an extra mount? Where do you get the config file from? I guess it should be a configmap 🤔 

@provokateurin interested in your thoughts as well.

**Comment by georglauterbach** [comment]
> I think to accommodate this, we'd need to have this be configurable in the [apache docker container](https://github.com/nextcloud/docker/blob/master/27/apache/Dockerfile) thinking

I knew about the `fpm` version, but is there another image flavor next to the Apache and `fpm` flavors?
 
> @georglauterbach can you post an example of what you did? Is it just an extra mount? Where do you get the config file from? I guess it should be a configmap thinking

Indeed, it is a `ConfigMap` I created manually. I mount it via

```yaml
extraVolumes:
  - name: extra-configuration-files
    configMap:
      name: extra-configuration-files

extraVolumeMounts:
  - name: extra-configuration-files
    subPath: ports.conf
    mountPath: /etc/apache2/ports.conf
    readOnly: true
```

in `values.yaml`.

**Comment by georglauterbach** [comment]
> > I knew about the fpm version, but is there another image flavor next to the Apache and fpm flavors?
> 
> There is the regular apache flavor and `fpm`, but there's also a `fpm-alpine` version as well :) You can see all the tags here: https://hub.docker.com/_/nextcloud/

I see, thanks! 👍🏼

> For your solution, that seems ok doable 🤔 Do you want to submit a PR for that? If not, it'll probably be a few days before I have some time to write out a solution and test it quickly.

I have close to zero time at the moment, so I cannot provide a PR. I'd really appreciate if you could provide a PR:) When you do, please also try to provide the `ServerName` part 🙈

**Comment by devthejo** [comment]
I got it to work as rootless using this config:
```yaml
image:
  tag: 27.1.3-fpm # https://hub.docker.com/r/library/nextcloud/tags/
nextcloud:
  host: "nextcloud.mydomain.tld"
  configs:
    custom.config.php: |
      <?php
        $CONFIG = array(
          "check_data_directory_permissions"=> false, # fix data directory permissions error
          "trusted_domains" => array (
            $_ENV["NEXTCLOUD_TRUSTED_DOMAINS"], # fix probes 400 error
          ),
        );
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
  containerPort: 8080
  extraVolumes:
  - name: nginx-cache
    emptyDir: {}
  extraVolumeMounts:
  - name: nginx-cache
    mountPath: "/var/cache/nginx" # fix permission denied error
nginx:
  ## You need to set an fpm version of the image for nextcloud if you want to use nginx!
  enabled: true
  image:
    repository: nginxinc/nginx-unprivileged
    tag: 1.25.3 # https://hub.docker.com/r/nginxinc/nginx-unprivileged/tags
  containerPort: 8080
```
