### ISSUE TITLE
dbpassword value doesn't match sealed secret

### ISSUE THREAD

**Issue by gizmo15** [nextcloud/helm#364]
Hi,

I use the helm chart 3.5.0 with mariadb.

I try to use sealed secret to handle the mysql password with this configuration :
```
  externalDatabase:
    enabled: true

    ## Supported database engines: mysql or postgresql
    type: mysql

    ## Database host
    host: kubetest-mariadb:3306

    ## Database user
    # user: nextcloud

    ## Database password
    # password: nextcloud

    ## Database name
    database: nextcloud

    ## Use a existing secret
    existingSecret:
      enabled: true
      secretName: nextcloudsecrets
      usernameKey: db_user
      passwordKey: db_password
```

But when i check the config.php in the pod, i have a dbpassword value completely different.

This is my sealed secret :
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloudsecrets
  namespace: nextcloud
spec:
  encryptedData:
    db_password: XXXXXXXXXX
    db_user: XXXXXXXXXX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nextcloudsecrets
      namespace: nextcloud
```

I don't understand what i missed. Can you help me on that ?

Thanks!
