### ISSUE TITLE
App deployment is using emptyDir instead of existing PVC defined in values.yaml, manually adding PVC results in container crashing "Initializing Nextcloud"

### ISSUE THREAD

**Issue by cjchico** [nextcloud/helm#380]
## Describe your Issue
The deployment is not using the existing PVC (created through Longhorn) that is defined in values.yaml. Instead, it defaults to using emptyDir.

### Logs and Errors
Rancher does not show any logs for the deployment or container. All events are normal and "Initializing Nextcloud."
The container continually crashes at a "CrashLoopBackOff" status if I add the PVC manually through the Rancher deployment.

## Describe your Environment

K3s, Helm 3.90, Nextcloud chart 3.5.9

values.yaml:
```yaml
affinity: {}
cronjob:
  enabled: false
  lifecycle: {}
  resources: {}
  securityContext: {}
deploymentAnnotations: {}
deploymentLabels: {}
externalDatabase:
  database: nextcloud
  enabled: false
  existingSecret:
    enabled: false
  host: null
  password: null
  type: mysql
  user: nextcloud
fullnameOverride: ''
hpa:
  cputhreshold: 60
  enabled: true
  maxPods: 6
  minPods: 1
image:
  pullPolicy: IfNotPresent
  repository: nextcloud
ingress:
  annotations: {}
  enabled: true
  labels: {}
  path: /
  pathType: Prefix
internalDatabase:
  enabled: true
  name: nextcloud
lifecycle: {}
livenessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
mariadb:
  architecture: standalone
  auth:
    database: nextcloud
    existingSecret: ''
    password: changeme
    username: nextcloud
  enabled: false
  primary:
    persistence:
      accessMode: ReadWriteMany
      enabled: false
      size: 8Gi
metrics:
  enabled: false
  https: false
  image:
    pullPolicy: IfNotPresent
    repository: xperimental/nextcloud-exporter
    tag: 0.6.0
  replicaCount: 1
  service:
    annotations:
      prometheus.io/port: '9205'
      prometheus.io/scrape: 'true'
    labels: {}
    type: ClusterIP
  serviceMonitor:
    enabled: false
    interval: 30s
    jobLabel: ''
    labels: {}
    namespace: ''
    scrapeTimeout: ''
  timeout: 5s
  tlsSkipVerify: false
  token: ''
nameOverride: ''
nextcloud:
  configs: {}
  datadir: /var/www/html/data
  defaultConfigs:
    .htaccess: true
    apache-pretty-urls.config.php: true
    apcu.config.php: true
    apps.config.php: true
    autoconfig.php: true
    redis.config.php: true
    smtp.config.php: true
  existingSecret:
    enabled: false
  extraEnv: null
  extraInitContainers: []
  extraSidecarContainers: []
  extraVolumeMounts: null
  extraVolumes: null
  host: nextcloud.local
  mail:
    domain: domain.com
    enabled: false
    fromAddress: user
    smtp:
      authtype: LOGIN
      host: domain.com
      name: user
      password: pass
      port: 465
      secure: ssl
  password: changeme
  persistence:
    subPath: null
    accessMode: ReadWriteMany
    enabled: true
    existingClaim: nextcloud-pvc
    storageClassName: longhorn
    size: 10Gi
  phpConfigs: {}
  podSecurityContext: {}
  securityContext: {}
  strategy:
    type: Recreate
  update: 0
  username: admin
nginx:
  config:
    default: true
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: alpine
  resources: {}
  securityContext: {}
nodeSelector: {}
persistence:
  accessMode: ReadWriteMany
  annotations: {}
  enabled: false
  nextcloudData:
    accessMode: ReadWriteMany
    annotations: {}
    enabled: false
    size: 8Gi
    subPath: null
  size: 8Gi
phpClientHttpsFix:
  enabled: false
  protocol: https
podAnnotations: {}
postgresql:
  enabled: false
  global:
    postgresql:
      auth:
        database: nextcloud
        existingSecret: ''
        password: changeme
        secretKeys:
          adminPasswordKey: ''
          replicationPasswordKey: ''
          userPasswordKey: ''
        username: nextcloud
  primary:
    persistence:
      enabled: false
rbac:
  enabled: false
  serviceaccount:
    annotations: {}
    create: true
    name: nextcloud-serviceaccount
readinessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
redis:
  auth:
    enabled: true
    existingSecret: ''
    existingSecretPasswordKey: ''
    password: changeme
  enabled: false
replicaCount: 1
resources: {}
securityContext: {}
service:
  loadBalancerIP: nil
  nodePort: nil
  port: 8080
  type: ClusterIP
startupProbe:
  enabled: false
  failureThreshold: 30
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
tolerations: []
global:
  cattle:
    systemProjectId: p-46shd
```

## Additional context, if any
I am using Longhorn to create the PVC with the following settings:

Volume Name: nextcloud
Size: 15Gi
Number of replicas: 3
Frontend: Block Device
Data Locality: Disabled
Access Mode: ReadWriteMany
Replicas Auto Balance: ignored
Persistent Volume Name: nextcloud-pvc
Persistent Volume Claim Name: nextcloud-pvc

*NFS services are installed and working on the nodes, I have confirmed successful RWX deployments.
