### ISSUE TITLE
Syntax error nextcloud/templates/deployment.yaml: line 57

### ISSUE THREAD

**Issue by arima0k** [nextcloud/helm#394]
## Describe your Issue
Error wen deploy: 
Error: INSTALLATION FAILED: YAML parse error on nextcloud/templates/deployment.yaml: error converting YAML to JSON: yaml: line 57: found character that cannot start any token

### Logs and Errors
Error: INSTALLATION FAILED: YAML parse error on nextcloud/templates/deployment.yaml: error converting YAML to JSON: yaml: line 57: found character that cannot start any token

## Describe your Environment

- Kubernetes distribution: k3s

- Helm Version (or App that manages helm): 3.11.3

- Helm Chart Version: latest
- `values.yaml`:

```yaml
image:
  repository: nextcloud
  # tag: 24.0.3-apache
  pullPolicy: IfNotPresent
  # pullSecrets:
  #   - myRegistrKeySecretName
```
