### ISSUE TITLE
Incorrect hard-coded database host when using Bitnami subcharts

### ISSUE THREAD

**Issue by JohnLahr** [nextcloud/helm#406]
## Describe your Issue
When using an external database, if either of the Bitnami subcharts for MariaDB or PostgreSQL are set up in replication mode, the Nextcloud init container will fail because it's using a hard-coded DB hostname value: `--host=%s-mariadb` or `-h %s-postgresql`. Neither of these take into account the fact that if you enable replication on the Bitnami MariaDB chart, for example, it creates service names `nextcloud-mariadb-primary` and `nextcloud-mariadb-secondary`, but no `nextcloud-mariadb`, as expected by the `mariadb-isalive` container.

### Logs and Errors
The `mariadb-isalive` container in the `nextcloud-*` pods get stuck with these logs repeating ad infinitum:

```
ERROR 2005 (HY000): Unknown server host 'nextcloud-mariadb' (-2)
waiting for mysql
```

## Describe your Environment

- Kubernetes distribution: confirmed on both EKS and baremetal

- Helm Version (or App that manages helm): ArgoCD v2.7.3 running Helm v3.11.2 (EKS) and Helm v3.12.0 (baremetal)

- Helm Chart Version: 3.5.13

- `values.yaml`:

```yaml
# --------------------------------------------------------------------------- #
# Nextcloud                                                                   #
# --------------------------------------------------------------------------- #

nextcloud:
  host: nextcloud.[REDACTED]
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  securityContext:
    runAsUser: 1020
    runAsGroup: 1005
    runAsNonRoot: true

# --------------------------------------------------------------------------- #
# Database                                                                    #
# --------------------------------------------------------------------------- #

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: mysql
  host: nextcloud-mariadb-primary
  database: nextcloud
  existingSecret:
    secretName: nextcloud-secrets
    usernameKey: mariadb-username
    passwordKey: mariadb-password

mariadb:
  enabled: true
  auth:
    database: nextcloud
    username: nextcloud
    existingSecret: nextcloud-secrets
  architecture: replication
  primary:
    persistence:
      enabled: true
      existingClaim: nextcloud-mariadb-persistence
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 8Gi

# --------------------------------------------------------------------------- #
# Redis                                                                       #
# --------------------------------------------------------------------------- #

redis:
  enabled: true
  clusterDomain: [REDACTED (NON-DEFAULT)]
  auth:
    enabled: true
    existingSecret: nextcloud-secrets
    existingSecretPasswordKey: redis-password

# --------------------------------------------------------------------------- #
# Resources                                                                   #
# --------------------------------------------------------------------------- #

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

# --------------------------------------------------------------------------- #
```

## Additional context, if any
I did set the value of `externalDatabase.host` to the correct service name `nextcloud-mariadb-primary`, but this still fails because these lines in [_helpers.tpl](https://github.com/nextcloud/helm/blob/88f0f4379ca984c98be9c4f44a5fb313f5a55037/charts/nextcloud/templates/_helpers.tpl#L77) are overwriting it:

```
 76  {{- else if .Values.mariadb.enabled }}
 77  - name: MYSQL_HOST
 78    value: {{ template "mariadb.primary.fullname" .Subcharts.mariadb }}
...
126    {{- else }}
127  - name: MYSQL_HOST
128    value: {{ .Values.externalDatabase.host | quote }}
```
