### ISSUE TITLE
Nextcloud Helm chart - unable to specify storageClass for Redis PVC

### ISSUE THREAD

**Issue by melbruki** [nextcloud/helm#424]
Hello,

I have encountered an issue with the Nextcloud Helm chart where I cannot specify a custom storageClass for Redis' PersistentVolumeClaim. I am using the rook-ceph-block storageClass in my environment, and while I'm able to set this for other parts of the application, Redis stays in a pending state, stating that no storage class is available.

Steps to reproduce:

I modified the values.yaml file to include:

```
redis:
  enabled: true
  auth:
    enabled: true
    password: "97176124"
  persistence:
    enabled: true
    storageClass: "rook-ceph-block"
    accessModes:
      - ReadWriteOnce
    size: 2Gi
```
Ran helm upgrade nextcloud nextcloud/nextcloud -f values.yaml.

Checked the PVCs with kubectl get pvc and found that the Redis PVCs remain in the Pending state.

Ran kubectl describe pvc redis-data-nextcloud-redis-master-0 and found the error message: no persistent volumes available for this claim and no storage class is set.

I attempted to install the Redis helm chart separately with the same settings and it worked as expected, but this issue occurs when Redis is a subchart of Nextcloud. I suspect that there might be a problem with the inheritance or propagation of the storageClass setting to the subchart.

Please could you investigate this further? I would appreciate any guidance or workaround that you can provide in the meantime.

Thank you.

**Comment by jessebot** [comment]
Thanks for reaching out!

I don't think we actually create those volumes directly. I'm pretty sure that it gets passed down to the bitnami chart directly, but others are free to correct me if I'm wrong. 🤔 

Here's a quick search of redis in this repo:
https://github.com/search?q=repo%3Anextcloud%2Fhelm%20redis&type=code

There are only 4 instances of `storageClass` defined in the bitnami redis subchart, and none of them are at the root level:
https://github.com/bitnami/charts/tree/main/bitnami/redis

There's the following available
- `global.storageClass`
- `master.persistence.storageClass`
- `replica.persistence.storageClass`
- `sentinel.persistence.storageClass`

so each of these would be under redis in your values.yaml like:
```yaml
redis:
  global:
    storageClass: "local-path"
```

Let me know if that helps, or if using those values also fails. Is our values.yaml or README out of date on this btw?
