### ISSUE TITLE
Nextcloud pods failed with  EFS as persistent volume

### ISSUE THREAD

**Issue by SerhiiK** [nextcloud/helm#433]
## Describe your Issue
Nextcldoud can't work properly with EFS as persistent volume through user and group issues.

### Logs and Errors
If use default storageClass faced permission issue

<details>
   <summary>Logs</summary>
     
![image](https://github.com/nextcloud/helm/assets/6170876/f2875442-682c-45d7-a536-bb7697550c09)

</details>

Efs driver by default can use random POSIX user id and group id. In this example is 1004:1004. 
Try to fix it by creating special storageClass with parameters[ uid and gid](https://github.com/kubernetes-sigs/aws-efs-csi-driver#storage-class-parameters-for-dynamic-provisioning)
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-nextcloud
mountOptions:
  - tls
parameters:
  basePath: /dynamic_provisioning
  directoryPerms: '700'
  fileSystemId: fs-[ID]
  gid: '33'
  provisioningMode: efs-ap
  uid: '33'
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```
After it all files has owner www-data:www-data but nextcloud show next logs: 

<details>

<summary>Logs</summary>

```
crond: crond (busybox 1.30.1) started, log level 0
crond: user:www-data entry:(null)
100001000010000100001000010000100001000010000100001000010000
111111111111111111111111
11111111111111111111111111111111
111111111111
1111111
crond: user:www-data entry:(null)
100001000010000100001000010000100001000010000100001000010000
111111111111111111111111
11111111111111111111111111111111
111111111111
1111111
crond: wakeup dt=48
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  job: 0 php -f /var/www/html/cron.php
crond: child running /bin/bash
crond: USER www-data pid   7 cmd php -f /var/www/html/cron.php

Warning: require_once(/var/www/html/lib/versioncheck.php): Failed to open stream: No such file or directory in /var/www/html/cron.php on line 40

Fatal error: Uncaught Error: Failed opening required '/var/www/html/lib/versioncheck.php' (include_path='.:/usr/local/lib/php') in /var/www/html/cron.php:40
Stack trace:
#0 {main}
  thrown in /var/www/html/cron.php on line 40
crond: wakeup dt=10
crond: wakeup dt=50
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
```
Nextcloud container in pod can't pass probes and failed. 
</details>

## Describe your Environment

- Kubernetes distribution: EKS 1.23.17

- Use efs csi driver with dynamic provisioning

- Helm Chart Version: 3.5.1

- `values.yaml`:

```yaml
      persistence:
        enabled: true
        storageClass: "efs-nextcloud"
        accessMode: ReadWriteMany
```
