### ISSUE TITLE
Nextcloud seems to not be able to connect to redis with default settings

### ISSUE THREAD

**Issue by jvalskis** [nextcloud/helm#448]
## Describe your Issue
I have an issue with Nextcloud failing to connect to redis when it's enabled. Here's an excerpt from the logs:
>{"reqId":"b8E9pguPPMd2bgHNOOj0","level":3,"time":"2023-09-26T06:14:19+00:00","remoteAddr":"10.42.5.1","user":"--","app":"PHP","method":"GET","url":"/status.php","message":"session_start(): Failed to read session data: redis (path: tcp://nextcloud-redis-master:6379?auth=\<redacted\>) at /var/www/html/lib/private/Session/Internal.php#222","userAgent":"kube-probe/1.27","version":"27.1.1.0","data":{"app":"PHP"}}

Which is weird, because when I do nslookup, it seems to resolve fine:
```bash
$ nslookup nextcloud-redis-master
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   nextcloud-redis-master.cloud.svc.cluster.local
Address: 10.43.32.88
```

What I did as a workaround, was to hardcode the "host" part in `redis.config.php` as such: `'host' => "nextcloud-redis-master.cloud.svc.cluster.local",`. Any ideas what might be wrong here?

## Describe your Environment

- Kubernetes distribution: `k3s`

- Helm Version (or App that manages helm): `3.11.0`

- Helm Chart Version: `3.5.22`

- `values.yaml`:

```yaml 
nextcloud:
  defaultConfigs:
    redis.config.php: false
  configs:
    redis.config.php: |-
      <?php
      $CONFIG = array (
        'memcache.distributed' => '\OC\Memcache\Redis',
        'memcache.locking' => '\OC\Memcache\Redis',
        'redis' => array(
          'host' => "nextcloud-redis-master.cloud.svc.cluster.local",
          'port' => getenv('REDIS_HOST_PORT') ?: 6379,
          'password' => getenv('REDIS_HOST_PASSWORD'),
        ),
      );
redis:
    enabled: true
    usePassword: true
    auth:
      existingSecret: nextcloud-auth-config
      existingSecretPasswordKey: redis-password
    master:
      persistence:
        storageClass: longhorn-fast-retain
    replica:
      persistence:
        storageClass: longhorn-fast-retain
```

**Comment by jessebot** [comment]
I haven't had time to look into this fully, but wanted to give some more details to help others troubleshoot:

Here's where the full name is defined in our templates, specifically `_helpers.tpl`:
https://github.com/nextcloud/helm/blob/0c6822fd688124124efb02a328f53b71cbdeb2a9/charts/nextcloud/templates/_helpers.tpl#L26-L32

and it gets referenced again here in our `_helpers.tpl`:
https://github.com/nextcloud/helm/blob/0c6822fd688124124efb02a328f53b71cbdeb2a9/charts/nextcloud/templates/_helpers.tpl#L215-L232

@jvalskis when it is unable to connect, could you please log into the container and check the environment variable called `REDIS_HOST`? Should be something like this to get it:

```bash
# where NEXTCLOUD_POD is the actual name of your nextcloud pod
kubectl exec $NEXTCLOUD_POD -- env | grep REDIS_HOST
```

**Comment by Kaurin** [comment]
I can replicate the error on my k3s cluster, but the timestamp shows that it happens within 60 seconds of the pod being started so it could be down to just redis not being ready?

I logged in/logged out a few times and the error does not repeat.

```json
{
  "reqId": "sGLjn5exo0J3ZAYR8Fde",
  "level": 3,
  "time": "2024-05-07T04:29:39+00:00",
  "remoteAddr": "10.42.0.1",
  "user": "--",
  "app": "PHP",
  "method": "GET",
  "url": "/status.php",
  "message": "session_start(): Redis connection not available at /var/www/html/lib/private/Session/Internal.php#213",
  "userAgent": "kube-probe/1.28",
  "version": "29.0.0.19",
  "data": {
    "app": "PHP"
  }
}
```

values.yml used:

```yaml
redis:
    enabled: true
```

**Comment by Kaurin** [comment]
Welp. I don't know if theissue is the same as OPs, but initially my redis password contained quite a few special characters.

Before doing anything else, I changed that password to non-special chars. Uninstall, clean PVCs and Volumes, install again without changing values.yml, and it works fine.

Current, working values.yml

```
redis:
    enabled: true
    usePassword: true
    auth:
      existingSecret: nextcloud-redis
      existingSecretPasswordKey: redisPw
```
