### ISSUE TITLE
Unable to adjust max upload size via PHP settings

### ISSUE THREAD

**Issue by mike12806** [nextcloud/helm#456]
## Describe your Issue

Not seeing a change in max upload size despite custom PHP setting (would expect to see 1024 MB here, not 512 MB) 

![Screenshot 2023-10-29 at 3 10 21 PM](https://github.com/nextcloud/helm/assets/80599490/0ecc51a0-4553-43f1-9012-87f939790c98)

## Describe your Environment

- Kubernetes distribution: 

K3S w/ Rancher 

- Helm Version (or App that manages helm): 

Helm w/ Rancher (Rancher 2.7.9 / Helm 3.11.3)

- Helm Chart Version: 

4.3.6

- `values.yaml`:

```yaml
affinity: {}
cronjob:
  enabled: true
  lifecycle: {}
  resources: {}
  securityContext: {}
  failedJobsHistoryLimit: 2
deploymentAnnotations: {}
deploymentLabels: {}
externalDatabase:
  database: nextcloud
  enabled: true
  existingSecret:
    enabled: false
  host: null
  password: $Secret
  type: postgres
  user: nextcloud
fullnameOverride: ''
hpa:
  cputhreshold: 75
  enabled: false
  maxPods: 10
  minPods: 1
image:
  pullPolicy: Always
  repository: nextcloud
  flavor: apache
  tag: stable
ingress:
  annotations: {}
  enabled: false
  labels: {}
  path: /
  pathType: Prefix
internalDatabase:
  enabled: false
  name: nextcloud
lifecycle:
  postStart:
    exec: 'command: ["/bin/bash", "-c", "apt update -y && apt install ffmpeg -y"]'
livenessProbe:
  enabled: true
  failureThreshold: 10
  initialDelaySeconds: 60
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 5
mariadb:
  architecture: null
  auth:
    database: nextcloud
    existingSecret: ''
    password: $Secret
    username: nextcloud
    rootPassword: $Secret
  enabled: false
  primary:
    persistence:
      accessMode: ReadWriteOnce
      enabled: true
      size: 16Gi
      storageClass: longhorn
metrics:
  enabled: false
  https: false
  image:
    pullPolicy: IfNotPresent
    repository: xperimental/nextcloud-exporter
    tag: latest
  replicaCount: 1
  service:
    annotations:
      prometheus.io/port: '9205'
      prometheus.io/scrape: 'true'
    labels: {}
    type: ClusterIP
  serviceMonitor:
    enabled: true
    interval: 30s
    jobLabel: ''
    labels: {}
    namespace: ''
    scrapeTimeout: ''
  timeout: 5s
  tlsSkipVerify: true
  token: ''
nameOverride: ''
nextcloud:
  configs: {}
  containerPort: 80
  datadir: /var/www/html/data
  defaultConfigs:
    .htaccess: true
    apache-pretty-urls.config.php: true
    apcu.config.php: true
    apps.config.php: true
    autoconfig.php: true
    redis.config.php: true
    smtp.config.php: true
  existingSecret:
    enabled: false
  extraEnv: null
  extraInitContainers: []
  extraSidecarContainers: []
  extraVolumeMounts: null
  extraVolumes: null
  host: $Secret
  mail:
    domain: gmail.com
    enabled: true
    fromAddress: $Secret
    smtp:
      authtype: LOGIN
      host: smtp.gmail.com
      name: $Secret
      password: $Secret
      port: 465
      secure: ssl
  password: $Secret
  persistence:
    subPath: null
    storageClass: longhorn
  phpConfigs:
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array(
          0 => '192.168.1.0/24',
          1 => '10.0.0.0/8',
        ),
        'trusted_domains' => array(
          0 => '$Secret',
          1 => '$Secret',
        ),
        'overwrite.cli.url' => '$Secret'
        'overwriteprotocol' => 'https'
        'filelocking.enabled' => 'true',
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
        'php_value upload_max_filesize' => '1024M',
        'php_value post_max_size' => '1024M',
        'php_value max_memory_size' => '1024M',
        'php_value max_input_time' => '3600s',
        'php_value max_execution_time' => '3600s',
        'default_phone_region' => 'US',
        'enable_previews' => 'true',
        'enabledPreviewProviders' => array (
          0 => 'OC\Preview\Movie',
          1 => 'OC\Preview\PNG',
          2 => 'OC\Preview\JPEG',
          3 => 'OC\Preview\GIF',
          4 => 'OC\Preview\BMP',
          5 => 'OC\Preview\XBitmap',
          6 => 'OC\Preview\MP3',
          7 => 'OC\Preview\MP4',
          8 => 'OC\Preview\TXT',
          9 => 'OC\Preview\MarkDown',
          10 => 'OC\Preview\PDF',
        ),     
  podSecurityContext: {}
  securityContext: {}
  strategy:
    type: Recreate
  update: 0
  username: admin
nginx:
  config:
    default: true
  containerPort: 8081
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: alpine
  resources: {}
  securityContext: {}
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  annotations: {}
  enabled: true
  nextcloudData:
    accessMode: ReadWriteOnce
    annotations: {}
    enabled: true
    size: 600Gi
    subPath: null
    storageClass: longhorn
  size: 300Gi
  storageClass: longhorn
phpClientHttpsFix:
  enabled: true
  protocol: https
podAnnotations: {}
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        database: nextcloud
        existingSecret: ''
        password: $Secret
        secretKeys:
          adminPasswordKey: $Secret
          replicationPasswordKey: $Secret
          userPasswordKey: $Secret
        username: nextcloud
  primary:
    persistence:
      enabled: true
  persistence:
    enabled: true
    storageClass: longhorn
  postgresqlUsername: nextcloudpostgres
rbac:
  enabled: false
  serviceaccount:
    annotations: {}
    create: true
    name: nextcloud-serviceaccount
readinessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
redis:
  auth:
    enabled: true
    existingSecret: null
    existingSecretPasswordKey: null
    password: $Secret
  enabled: true
replicaCount: 1
resources: {}
securityContext: {}
service:
  loadBalancerIP: 192.168.1.2
  nodePort: nil
  port: 9000
  type: LoadBalancer
startupProbe:
  enabled: true
  failureThreshold: 30
  initialDelaySeconds: 300
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
tolerations: []
global:
  cattle:
    systemDefaultRegistry: ''
    systemProjectId: p-n4j7m
  systemDefaultRegistry: ''
```

## Additional context, if any

I'm using NGINX proxy manager with a custom config applied to the nextcloud host

```
fastcgi_request_buffering off;
proxy_read_timeout 3600;
proxy_connect_timeout 3600; 
proxy_send_timeout 3600;
client_max_body_size 1024m;
sendfile_max_chunk 1024m;
sendfile on;
send_timeout 3600;
fastcgi_send_timeout 3600;
fastcgi_connect_timeout 3600;
fastcgi_read_timeout 3600;
keepalive_timeout 3600;
client_header_timeout 3600;
client_body_timeout 3600;
lingering_timeout 3600;
lingering_close on;
lingering_time 3600;
proxy_buffering off;
location = /.well-known/carddav {
        return 301 https://$host/remote.php/dav;
    }

    location = /.well-known/caldav {
        return 301 https://$host/remote.php/dav;
    }
```
