### ISSUE TITLE
Manage apps with initContainer

### ISSUE THREAD

**Issue by wrenix** [nextcloud/helm#466]
i like to add a easy mechanis to setup and configure appplication.

so i see the following new options in `values.yaml`:

```yaml 
nextcloud:
  appManagement:
    # -- if app not listed under apps it will be disabled
    autoDisable: true
    # -- if app not listed under apps it will be uninstalled
    autoUninstall: true
    apps:
       deck:
         enabled: true
       drawio:
          enabled: true
          config:
            DrawioUrl: "https://embed.diagrams.net"
            DrawioOffline: "yes"
```

Therefore
- i will use the occ command with an initContainer for enable and check there installation
- `nextcloud.appManagement.apps` is an dict for easy use multiple `value.yaml` files and merge them
 - config of applications are stored in an kubernetes-secret because they could containe sensitiv informations
