### ISSUE TITLE
feature: add `nextcloud.objectStore.s3` section in the values.yaml

### ISSUE THREAD

**Issue by jessebot** [nextcloud/helm#477]
Perhaps it makes sense to have a `nextcloud.objectStore.s3` section in the values.yaml like (maybe in a second PR as I'd need to play with the deployment template and add an s3 secret):

```yaml
nextcloud:
  objectStore:
    s3:
      enabled: true
      # ignored if nextcloud.objectstore.s3.existingSecret is not empty string
      accessKey: ""
      # ignored if nextcloud.objectstore.s3.existingSecret is not empty string
      secretKey: ""
      # only required if you're not using AWS
      endpoint: ""
      # default port that can be changed based on your object store, e.g. for minio, you can use 9000
      port: "443"
      # this is the default in the nextcloud docs
      region: "eu-west-1"
      bucket: ""
      ssl: true
      # set to true if you are not using DNS for your buckets.
      usePathStyle: false
      existingSecret: ""
```

_Originally posted by @jessebot in https://github.com/nextcloud/helm/issues/464#issuecomment-1817840422_
