### ISSUE TITLE
Environment Variables Parsed From Secrets Get a Newline Appended

### ISSUE THREAD

**Issue by zumbrunnen** [nextcloud/helm#490]
## Describe your Issue

The bug has been detected because sending mails stopped working. The error message in `nextcloud.log`:

```
Connection could not be established with host "smtp.sendgrid.net\n:587": stream_socket_client(): php_network_getaddresses: getaddrinfo for smtp.sendgrid.net\n failed: Name or service not known
```
:point_up:  Note the `\n` between host and port.

Indeed, all environment variables that are parsed from a Kubernetes secret get a newline at the end of their value. Here's en excerpt of `env` on the container:

```env
NEXTCLOUD_ADMIN_PASSWORD=xxxxxxxxxx

KUBERNETES_PORT_443_TCP_ADDR=10.76.0.1
SMTP_PASSWORD=xxxxxxxxxx

APACHE_ENVVARS=/etc/apache2/envvars
KUBERNETES_SERVICE_HOST=10.76.0.1
KUBERNETES_PORT=tcp://10.76.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
S3_SECRET=xxxxxxxxxx

NEXTCLOUD_PORT_8080_TCP=tcp://10.76.8.192:8080
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SMTP_HOST=smtp.sendgrid.net

NEXTCLOUD_PORT=tcp://10.76.8.192:8080
``` 
:point_up: Note the empty lines, caused by the trailing newline in the previous value.

This bug seems to be related to #475. But I'm not sure which version/change introduced it.

### Logs and Errors

See above. The `nextcloud.log` is from the container under  `/var/www/html/data/nextcloud.log` (as this app does not bother to log to STDOUT :wink: )

## Describe your Environment

- Kubernetes distribution: GKE

- Helm Version (or App that manages helm): `version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}`

- Helm Chart Version: 4.5.4

- `values.yaml`:

```yaml
---
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: nextcloud
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: nextcloud
    networking.gke.io/v1beta1.FrontendConfig: nextcloud-frontend-config
  path: /*
  pathType: ImplementationSpecific
nextcloud:
  host: xxxxxxxxxx
  existingSecret:
    enabled: true
    secretName: nextcloud-credentials
    usernameKey: admin-username
    passwordKey: admin-password
    smtpUsernameKey: sendgrid-username
    smtpPasswordKey: sendgrid-password
    smtpHostKey: sendgrid-host
  extraEnv:
    - name: S3_KEY
      valueFrom:
        secretKeyRef:
          name: nextcloud-credentials
          key: s3-key
    - name: S3_SECRET
      valueFrom:
        secretKeyRef:
          name: nextcloud-credentials
          key: s3-secret
  mail:
    enabled: true
    fromAddress: no-reply
    domain: xxxxxxxxxx
    smtp:
      host: smtp.sendgrid.net
      port: 587
      secure: tls
      authtype: LOGIN
  configs:
    proxies.config.php: |-
      <?php
      $CONFIG = array (
        'overwriteprotocol' => 'https'
      );
    s3.config.php: |-
      <?php
      $CONFIG = array (
        'objectstore' => array(
          'class' => '\\OC\\Files\\ObjectStore\\S3',
          'arguments' => array(
            'hostname'   => 'storage.googleapis.com',
            'bucket'     => 'xxxxxxxxxx',
            'key'        => getenv('S3_KEY'),
            'secret'     => getenv('S3_SECRET'),
            'use_ssl'         => true,
            'use_path_style'  => true
          )
        )
      );
    zzz-custom.config.php: |-
      <?php
      $CONFIG = array (
        'default_phone_region' => 'CH'
      );
  phpConfigs:
    zzz-custom.ini: |-
      upload_max_filesize=8G
      post_max_size=8G
      apc.enable_cli=1
      memory_limit=1024M
internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: mysql
  host: cloudsql-proxy:3306
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-credentials
    usernameKey: database-username
    passwordKey: database-password
cronjob:
  enabled: true
persistence:
  enabled: true
```
