### ISSUE TITLE
Feature: Setting for timezone in nextcloud-nginx container

### ISSUE THREAD

**Issue by Tha-Fox** [nextcloud/helm#494]
## Description of the change

Currently I can set the timezone for `nextcloud` container via `extraEnv` and installing `tzdata` in `postStartCommand`. However, I can't find any similar setting for `nextcloud-nginx` container in the Helm chart. This leads to situation, where `nextcloud` container is two hours "ahead" compared to `nextcloud-nginx` container.

I think the most straightforward way to add this feature would be adding similar `extraEnv` for `nextcloud-nginx` as there already is for `nextcloud` container, but I've got to admit that I'm no expert when it comes to Helm charts.

## Benefits

Troubleshooting is easier, when both containers have the same timezone.

## Additional information

I'm currently running Nextcloud with this configuration:

```yaml
image:
  repository: nextcloud
  tag: 27.1.4-fpm-alpine

lifecycle:
  postStartCommand:
    [
      "/bin/sh",
      "-c",
      "apk add tzdata",
      "&&",
      "crond",
    ]

nginx:
  ## You need to set an fpm version of the image for nextcloud if you want to use nginx!
  enabled: true
  image:
    repository: nginx
    tag: 1.21.6-alpine
```
    
I noticed that by default the timezone is UTC, but if I run manually `export TZ=Europe/Helsinki` inside `nextcloud-nginx` container, I get the correct time with `date`.
