### ISSUE TITLE
Helm Chart not properly configuring SMTP_SECURE, SMTP_HOST, SMTP_USER, SMTP_PASS and SMTP_PORT

### ISSUE THREAD

**Issue by Routhinator** [nextcloud/helm#510]
## Describe your Issue
When using the mail settings in the helm chart, many of the resulting values bound to the pods environment variables are defaults and not the configured settings.

The only ones that work properly are MAIL_DOMAIN, MAIL_FROM_ADDRESS and SMTP_AUTHTYPE.

### Logs and Errors
Errors: Email sending does not work. Validating the configuration by inspecting the pod yaml makes the problem clear.

From the nextcloud pod (fetched with `get pod -o=yaml`)

```yaml
    - name: MAIL_FROM_ADDRESS
      value: nextcloud
    - name: MAIL_DOMAIN
      value: private.com
    - name: SMTP_SECURE
      value: ssl
    - name: SMTP_PORT
      value: "465"
    - name: SMTP_AUTHTYPE
      value: LOGIN
    - name: SMTP_HOST
      valueFrom:
        secretKeyRef:
          key: smtp-host
          name: nextcloud
    - name: SMTP_NAME
      valueFrom:
        secretKeyRef:
          key: smtp-username
          name: nextcloud
    - name: SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          key: smtp-password
          name: nextcloud
```

From the nextcloud secret:
```
  smtp-host: ZG9tYWluLmNvbQ==
  smtp-password: cGFzcw==
  smtp-username: dXNlcg==

╭─ ~/projects/terraform
  
echo ZG9tYWluLmNvbQ== | base64 -d
domain.com%                                                                                                                                                                                                                          

╭─ ~/projects/terraform

echo cGFzcw== | base64 -d
pass%                                                                                                                                                                                                                                

╭─ ~/projects/terraform
echo dXNlcg== | base64 -d
user%   

```

From my values.yaml input:

```yaml
nextcloud:
  mail:
    enabled: true
    fromAddress: nextcloud
    domain: private.com
    stmp:
      host: smtp.private.com
      secure: "NONE"
      port: "587"
      authtype:  LOGIN
      name: nextcloud@private.com
      password: <omitted>
```

## Describe your Environment

- Kubernetes distribution: 1.27.1

- Helm Version (or App that manages helm): Terraform's helm provider: https://registry.terraform.io/providers/hashicorp/helm/latest/docs
- Helm Chart Version: 3.5.19

- `values.yaml`:

<!-- please keep the ```yaml part here, as it creates syntax highlighting to help with reading the file -->
```yaml
nextcloud:
  mail:
    enabled: true
    fromAddress: nextcloud
    domain: private.com
    stmp:
      host: smtp.private.com
      secure: "NONE"
      port: "587"
      authtype:  LOGIN
      name: nextcloud@private.com
      password: <omitted>
```

## Additional context, if any
<!-- Also note any additional relevant info about your environment. -->
<!-- example: If your issue is related to persistent volumes, let us know you're using NFS or EFS, for instance. -->
