### ISSUE TITLE
No is_alive init-conaiter  on external db 

### ISSUE THREAD

**Issue by DrummyFloyd** [nextcloud/helm#511]
## Describe your Issue
https://github.com/nextcloud/helm/blob/3b7b2f24ca5c8da56b4ad29b80e66ded4a6da69a/charts/nextcloud/templates/deployment.yaml#L276
https://github.com/nextcloud/helm/blob/3b7b2f24ca5c8da56b4ad29b80e66ded4a6da69a/charts/nextcloud/templates/deployment.yaml#L299
```yaml
      {{- if or .Values.nextcloud.extraInitContainers .Values.mariadb.enabled .Values.postgresql.enabled .Values.externalDatabase }}
      ....
      {{- if .or Values.mariadb.enabled (eq .Values.externalDatabase.type "mysql")  }}
      ....
      {{- else if .Values.postgresql.enabled (eq .Values.externalDatabase.type "postgresql") }}
```

there is such mecanism for db from chart dependencies 
but none form externalDB 
would be great to add the condition for the external db 

### Logs and Errors
none

## Describe your Environment

- Kubernetes distribution:OVH kubernetes

- Helm Version (or App that manages helm):  helm

- Helm Chart Version: 4.5.10

- `values.yaml`:
```yaml
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: "testwordpress.comodo3000.fr"
    path: /
    tls: true
    # secrets:
    #   - name: "testwordpress-secret"
  externalDatabase:
    host: mariadb.svc.cluster.local
    user: userwordpress
    password: xxxxxxx
    database: wordpress
    port: 3306
  mariadb:
    enabled: false
  wordpressUsername: admin
  wordpressPassword: dk435lej15466cCZE
  allowEmptyPassword: false
  persistent:
    selector:
      name: wordpress

```

## Additional context, if any
None
