### ISSUE TITLE
Can't start Nextcloud because the version of the data (0.0.0.0) is higher than the docker image version () and downgrading is not supported. Are you sure you have pulled the newest image version?

### ISSUE THREAD

**Issue by gregory112** [nextcloud/helm#569]
## Describe your Issue
CrashLoopBackOff on first install of Nextcloud helm. It's a new installation, why does this happen?

### Logs and Errors
```
Can't start Nextcloud because the version of the data (0.0.0.0) is higher than the docker image version () and downgrading is not supported. Are you sure you have pulled the newest image version?
```

## Describe your Environment

- Kubernetes distribution: bare metal

- Helm Version (or App that manages helm): 3.14.2, helmfile version 1.0.0-rc.0

- Helm Chart Version: 4.6.8

- `values.yaml` (my helmfile):

```yaml
repositories:
  - name: nextcloud
    url: https://nextcloud.github.io/helm/

releases:
  - name: nextcloud2
    namespace: default
    chart: nextcloud/nextcloud
    values:
      - image:
          tag: 27.1.9
      - resources:
          requests:
            memory: "1024Mi"
            cpu: "2000m"
      - nextcloud:
          host: nextcloud.example.com
      - internalDatabase:
          enabled: false
      - externalDatabase:
          enabled: true
          type: mysql
          host: 192.168.1.12:3306
          database: nextcloud2
          user: nextcloud
          password: nextcloud
      - persistence:
          enabled: true
          storageClass: csi-rbd-sc
          size: 150Gi
      - ingress:
          enabled: true
          className: nginx
          tls:
            - hosts:
                - nextcloud.example.com
              secretName: nextcloud.example.com-cert
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
#            nginx.ingress.kubernetes.io/enable-cors: "true"
#            nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
            nginx.ingress.kubernetes.io/server-snippet: |-
              server_tokens off;
              proxy_hide_header X-Powered-By;
              rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
              rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
              rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
              rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
              location = /.well-known/carddav {
                return 301 $scheme://$host/remote.php/dav;
              }
              location = /.well-known/caldav {
                return 301 $scheme://$host/remote.php/dav;
              }
              location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
              }
              location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
                deny all;
              }
              location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
                deny all;
              }

```
