### ISSUE TITLE
Include path in ingress

### ISSUE THREAD

**Issue by krisko** [nextcloud/helm#58]
Hi, could you please include option to configure path in ingress.yaml?

```
spec:
  rules:
  - host: {{ .Values.nextcloud.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "nextcloud.fullname" . }}
          servicePort: {{ .Values.service.port }}
        path: {{ .Values.ingress.path }}
```
