### ISSUE TITLE
file CAN_INSTALL is missing from your config directory

### ISSUE THREAD

**Issue by blinkiz** [nextcloud/helm#60]
I can not install Nextcloud with v2.5.0 Helm chart and configuration below.

#### Nextcloud pod logfile before first restart
```
Initializing nextcloud 19.0.3.1 ...
Initializing finished
New nextcloud instance
Installing with MySQL database
starting nextcloud installation
Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection timed out
 -> 
retrying install...
```
#### Error message in web gui
Nextcloud pod is restarting and does not continue with the installation. In web gui this message is displayed.
```
It looks like you are trying to reinstall your Nextcloud. However the file CAN_INSTALL is missing from your config directory. Please create the file CAN_INSTALL in your config folder to continue.
```
#### Configuration
```bash
nextcloud_hostname="nextcloud.example.com"
nextcloud_username="myusername"
nextcloud_password="my-password"
namespace="default"
nextcloud_helm_version="2.5.0"

helm repo add nextcloud https://nextcloud.github.io/helm/

```
```yaml
cat "nextcloud.override.yaml"
ingress:
  enabled: true
  tls:
    - secretName: nextcloud-tls
      hosts:
        - "${nextcloud_hostname}"
  annotations:
    kubernetes.io/ingress.class: "contour"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    ingress.kubernetes.io/force-ssl-redirect: "true"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi

nextcloud:
  host: "${nextcloud_hostname}"
  username: "${nextcloud_username}"
  password: "${nextcloud_password}"

  configs:
    custom.config.php: |-
      <?php
        \$CONFIG = array (
          'overwrite.cli.url' => "https://${nextcloud_hostname}",
          'overwritehost' => "${nextcloud_hostname}",
          'overwriteprotocol' => 'https',
        );

internalDatabase:
  enabled: false
  
mariadb:
  enabled: true
  
  master:
    persistence:
      enabled: true
      # storageClass: ""
      accessMode: ReadWriteOnce
      size: 8Gi
```
```bash

install_or_upgrade="install"
helm "${install_or_upgrade}" nextcloud nextcloud/nextcloud --namespace "${namespace}" \
--version "${nextcloud_helm_version}" --values "nextcloud.override.yaml"
```
#### Database
It is correct that the database is not yet up when Nextcloud is beginning is installation. Nextcloud needs to wait for it.

#### Solution
I do not know what the problem is but am guessing it's the lack of readiness probe against external dependencies.
* Bitnami mariadb has readiness probe status update which can be queried by a Init Container before nextcloud pod is allowed to start.
* Another solution would be to implement something like [wait-for-it](https://github.com/vishnubob/wait-for-it) in a init Container. 
* Best would be if Nextcloud installation would fail nicely so after restart of the nextcloud pod the installation will be retried.

**Comment by blinkiz** [comment]
This problem is probably related to #52 because I get the same error before described problem above.

**Comment by blinkiz** [comment]
Recently StartProbe was added to Nextcloud helm charts.
```yaml
startupProbe:
  enabled: true
```
This does not solve the initial problem but it makes Nextcloud fail in my case correctly. Meaning after a second retry the database is now up and nextcloud will successfully install itself understanding that it failed the first try and will not ask for CAN_INSTALL file.

**Comment by tcardonne** [comment]
Even with the `startupProbe` enabled, my Nextcloud deployment asks for the CAN_INSTALL file after failing because the included database is not ready on the first try.

Am I missing something or only something like #67 will fix this issue ?

**Comment by wikoion** [comment]
The `startupProbe` is an inconsistent solution. They delay will always need to be longer than it takes for the database to come up, if this takes longer than usual, because your cluster is waiting to claim resources for example, this will still fail. The `initContainer` solution actually checks if your container is ready. You can test my PR to see if it fixes the issue for you?

**Comment by xyhhx** [comment]
If anybody is still getting this, it's likely due to the same issue (installation being interrupted).

In my case, it helped to increase the settings for the readiness and liveness probes:

```yml
    startupProbe:
      enabled: true
      periodSeconds: 30
      failureThreshold: 10
    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      failureThreshold: 10
```

Also, if you're using an external database, and are managing it and this chart with kustomize, you can set the nextcloud kustomization to wait for the postgress customization using `dependsOn`. For example:

```yml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-postgresql-release
  namespace: flux-system
spec:
  path: ./kubernetes/workloads/nextcloud/postgresql/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-release
  namespace: flux-system
spec:
  path: ./kubernetes/workloads/nextcloud/nextcloud/release
  prune: true
  dependsOn:
    - name: nextcloud-postgresql-release
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
```
