### ISSUE TITLE
S3: `failed to create resource: [...] spec.template.spec.containers[1].env[22].valueFrom.secretKeyRef.key: Required value]`

### ISSUE THREAD

**Issue by unbelauscht** [nextcloud/helm#616]
## Describe your Issue
Installing Nextcloud with Helm chart version 5.5.2 results in

```
failed to create resource: Deployment.apps "nextcloud" is invalid: [spec.template.spec.containers[0].env[22].valueFrom.secretKeyRef.key: Required value, spec.template.spec.containers[1].env[22].valueFrom.secretKeyRef.key: Required value]
```

### Logs and Errors

Helm repo:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 3h0m0s
  url: https://nextcloud.github.io/helm
```

## Describe your Environment

- Kubernetes distribution: k3s v1.28.8+k3s1

- Helm Version (or App that manages helm):
```
$ flux version
flux: v2.3.0
distribution: flux-v2.3.0
helm-controller: v1.0.1
image-automation-controller: v0.38.0
image-reflector-controller: v0.32.0
kustomize-controller: v1.3.0
notification-controller: v1.3.0
source-controller: v1.3.0
```

- Helm Chart Version: 5.5.2

- `values.yaml`:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  timeout: 1h
  chart:
    spec:
      chart: nextcloud
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  interval: 12h
  values:
    replicaCount: 1
    image:
      flavor: apache
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-rw
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db
        usernameKey: username
        passwordKey: password
    startupProbe:
      enabled: true
      initialDelaySeconds: 20
      failureThreshold: 10
    ingress:
      enabled: true
      servicePort: 80
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: nextcloud-maxrequestbodybytes@kubernetescrd
        external-dns.alpha.kubernetes.io/target: drive.example.com
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      tls:
        - hosts:
            - drive.example.com
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
    redis:
      enabled: true
    nextcloud:
      host: drive.example.com
      objectStore:
        s3:
          enabled: true
          ssl: true
          port: "443"
          region: "eu-central-003"
          autocreate: false
          existingSecret: s3
          secretKeys:
            accessKey: accessKey
            secretKey: secretKey
            bucket: bucket
            host: host
      existingSecret:
        enabled: true
        secretName: nextcloud-user
        usernameKey: username
        passwordKey: password
      mail:
        enabled: false
    cronjob:
      enabled: true
    phpClientHttpsFix:
      enabled: true
      protocol: https
```

S3 credentials
```yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3
  namespace: nextcloud
spec:
  encryptedData:
    accessKey: *redacted*
    bucket: *redacted*
    host: *redacted*
    secretKey: *redacted*
  template:
    metadata:
      creationTimestamp: null
      name: s3
      namespace: nextcloud
```
