### ISSUE TITLE
Startup probe errored: strconv.Atoi: parsing "http": invalid syntax

### ISSUE THREAD

**Issue by sseneca** [nextcloud/helm#63]
Startup probe doesn't work for me.

Could be because of [this](https://github.com/nextcloud/helm/commit/24f9373984cfc1970778229a4fcc4e08b335415e#diff-9320b77c358085c20797303fd29b5f51cc0a94ee926042a12ba4e0011053deaaR210) line, which looks similar to [this](https://github.com/helm/helm/issues/4009) issue.

**Comment by webwurst** [comment]
Just from reading the template it looks like the named port `http` should only be defined for one container. Does it work for you when you use `80` instead in the startup probe?

**Comment by sseneca** [comment]
For which value do you want me to specify `80`? Doing something like

```yaml
    startupProbe:
      enabled: true
      httpGet:
        path: /status.php
        port: 80
        httpHeaders:
        - name: Host
          value: ...
```
doesn't override the values from the template
