### ISSUE TITLE
SMTP settings broken when using existingSecret

### ISSUE THREAD

**Issue by maxirus** [nextcloud/helm#64]
When `nextcloud.existingSecret.enabled` is set to true, the secret referenced by the below is **not** created and will cause NextCloud to not come up when SMTP is enabled.

```yaml
        - name: SMTP_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "nextcloud.fullname" . }}
              key: smtp-username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "nextcloud.fullname" . }}
              key: smtp-password
```
