### ISSUE TITLE
303 response code on login for fpm-alpine with mariadb

### ISSUE THREAD

**Issue by paulcosma** [nextcloud/helm#66]
Unable to login due to 303 response. 
Any suggestions on how to fix this? Thanks

Logs:
```bash
kubectl logs nextcloud-6ff79b69d6-vd4lw -c nextcloud -f
127.0.0.1 -  24/Jan/2021:06:13:23 +0000 "POST /index.php" 303
127.0.0.1 -  24/Jan/2021:06:13:23 +0000 "GET /index.php" 303
127.0.0.1 -  24/Jan/2021:06:13:23 +0000 "GET /index.php" 200
127.0.0.1 -  24/Jan/2021:06:13:24 +0000 "GET /cron.php" 200
```

Helm values:
```yaml
image:
  tag: 19.0.3-fpm-alpine
ingress:
  enabled: true
  tls:
    - secretName: nextcloud-tls
      hosts:
        - nextcloud.<my-domain>.com
  annotations: # Uncommented all values
nginx:
  enabled: true
internalDatabase:
  enabled: false  
mariadb:
  enabled: true
  replication:
    enabled: true
  master:
    persistence:
      enabled: true
      storageClass: "<my-nfs-storage-class>"
      accessMode: ReadWriteMany    
redis:
  enabled: true
persistence:
  enabled: true
  storageClass: "<my-nfs-storage-class>"
  accessMode: ReadWriteMany        
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
```
