### ISSUE TITLE
config.php is not regenerated on config changes

### ISSUE THREAD

**Issue by pfaelzerchen** [nextcloud/helm#660]
## Describe your Issue
I tried to migrate from the redis subchart to a redis-cluster deployment. Therefore, I added a custom redis.config.php, TLS certificates and an ENV for the password, deactivated the defaultConfig, disabled the redis-subchart and redeployed nextcloud - and got an Internal Server Error.

When investigating, I saw that /var/www/html/config/config.php has its own redis section pointing to the old server - which does not exist anymore:

```php
  'redis' => 
  array (
    'host' => 'nextcloud-redis-master',
    'password' => 'password',
    'port' => 6379,
  ),

```

### Logs and Errors
The log does not show any errors.

The config directory looks like this. One ca see, that config.php is 4 days older than any other file. The `redis.config.php` is empty here, because the defaultConfig and my custom redis.config.php are deactivated and redis works with the old entry in config.php. Before there was a redis-cluster.config.php with the same effect.

```
# ls -la /var/www/html/config
total 84
drwxrwsr-x  2 root     www-data 4096 Nov 28 15:21 .
drwxrwsr-x 16 www-data www-data 4096 Nov  9 20:48 ..
-rw-r--r--  1 root     www-data  261 Nov 28 15:23 .htaccess
-rw-r--r--  1 root     www-data   59 Nov 28 15:23 apache-pretty-urls.config.php
-rw-r--r--  1 root     www-data   69 Nov 28 15:23 apcu.config.php
-rw-r--r--  1 root     www-data  376 Nov 28 15:23 apps.config.php
-rw-r--r--  1 root     www-data 2106 Nov 28 15:23 autoconfig.php
-rw-rw----  1 www-data www-data 3631 Nov 24 16:02 config.php
-rw-r--r--  1 root     www-data  161 Nov 28 15:23 country.config.php
-rw-rw-r--  1 www-data www-data    2 Apr 27  2024 mimetypealiases.json
-rw-rw-r--  1 www-data www-data    2 Apr 27  2024 mimetypemapping.json
-rw-r--r--  1 root     www-data 1300 Nov 28 15:23 oidc.config.php
-rw-r--r--  1 root     www-data  179 Nov 28 15:23 oldinstance.config.php
-rw-r--r--  1 root     www-data   61 Nov 28 15:23 other.config.php
-rw-r--r--  1 root     www-data  319 Nov 28 15:23 proxy.config.php
-rwxrwxr-x  1 root     www-data    0 Dec 21  2023 redis.config.php
-rw-r--r--  1 root     www-data  797 Nov 28 15:23 reverse-proxy.config.php
-rw-r--r--  1 root     www-data 2313 Nov 28 15:23 s3.config.php
-rw-r--r--  1 root     www-data  932 Nov 28 15:23 smtp.config.php
-rw-r--r--  1 root     www-data 1102 Nov 28 15:23 swift.config.php
-rw-r--r--  1 root     www-data   94 Nov 28 15:23 updater.config.php
-rw-r--r--  1 root     www-data   59 Nov 28 15:23 upgrade-disable-web.config.php
```

## Describe your Environment

- Kubernetes distribution: k3s v1.30.6

- Helm Version (or App that manages helm): ArgoCD 2.13.1

- Helm Chart Version: 6.2.4

- `values.yaml`:

```yaml

        # Number of replicas to be deployed
        replicaCount: 1

        nextcloud:
          host: nextcloud.beispiel.de
          username: admin
          password: changeme
          ## Use an existing secret
          existingSecret:
            enabled: false
            secretName: nextcloud-secrets
            usernameKey: nextcloud-username
            passwordKey: nextcloud-password
            # tokenKey: nextcloud-token
            smtpUsernameKey: smtp-username
            smtpPasswordKey: smtp-password
            smtpHostKey: smtp-host
          update: 0
          # If web server is not binding default port, you can define it
          containerPort: 80
          datadir: /var/www/html/data
          mail:
            enabled: true
            fromAddress: nextcloud
            domain: beispiel.de
            smtp:
              host: smtp.beispiel.de
              secure: ssl
              port: 465
              authtype: LOGIN
              name: admin@beispiel.de

          phpConfigs:
            redis-session-locking.ini: |-
              redis.session.locking_enabled=1
              redis.session.lock_retries=-1
              redis.session.lock_wait_time=10000

          ## Default config files that utilize environment variables:
          # see: https://github.com/nextcloud/docker/tree/master#auto-configuration-via-environment-variables
          # IMPORTANT: Will be used only if you put extra configs, otherwise default will come from nextcloud itself
          # Default confgurations can be found here: https://github.com/nextcloud/docker/tree/master/.config
          defaultConfigs:
            # Redis default configuration
            redis.config.php: false

          # Extra config files created in /var/www/html/config/
          # ref: https://docs.nextcloud.com/server/15/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file
          configs:
            proxy.config.php: |-
              <?php
              $CONFIG = array (
                'trusted_proxies' => array(
                  0 => '127.0.0.1',
                  1 => '10.0.0.0/8',
                ),
                'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
                'overwritehost'     => 'nextcloud.beispiel.de',
                'overwriteprotocol' => 'https',
                'overwrite.cli.url' => 'https://nextcloud.beispiel.de'
              );
            country.config.php: |-
              <?php
              $CONFIG = array (
                'default_language' => 'DE',
                'default_phone_region' => 'DE',
                'default_locale' => 'de_DE',
                'default_timezone' => 'Europe/Berlin'
              );
            updater.config.php: |-
              <?php
              $CONFIG = array (
                'updatechecker' => false,
                'updater.release.channel' => 'stable'
              );
            other.config.php: |-
              <?php
              $CONFIG = array (
                'maintenance_window_start' => 22
              );
            redis.config.php: |-
              <?php
              $CONFIG = array (
                'memcache.distributed' => '\OC\Memcache\Redis',
                'memcache.locking' => '\OC\Memcache\Redis',

                'redis' => array(),
                'redis.cluster' => array (
                  'seeds' => array(
                    'redis-nextcloud.media-files.svc.cluster.local:6379'
                  ),
                  'timeout' => 0.0,
                  'read_timeout' => 0.0,
                  'failover_mode' => \RedisCluster::FAILOVER_ERROR,
                  'password' => getenv('REDIS_HOST_PASSWORD'),
                  // If redis in-transit encryption is enabled, provide certificates
                  // SSL context https://www.php.net/manual/en/context.ssl.php
                  'ssl_context' => array (
                          'local_cert' => '/opt/certs/redis/tls.crt',
                          'local_pk' => '/opt/certs/redis/tls.key',
                          'cafile' => '/opt/certs/redis/ca.crt'
                  )
                )
              );

          ##
          ## Extra environment variables
          extraEnv:
            - name: REDIS_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: redis-password

          # Extra mounts for the pods. Example shown is for connecting a legacy NFS volume
          # to NextCloud pods in Kubernetes. This can then be configured in External Storage
          extraVolumes:
            - name: oldinstance
              secret:
                secretName: nextcloud-secrets
                items:
                  - key: oldinstance.config.php
                    path: oldinstance.config.php
            - name: oidc
              secret:
                secretName: nextcloud-secrets
                items:
                  - key: oidc.config.php
                    path: oidc.config.php
            - name: redis-tls-certs
              secret:
                secretName: tls-redis-nextcloud
            - name: pictures
              persistentVolumeClaim:
                claimName: pictures
            - name: audio
              persistentVolumeClaim:
                claimName: audio
            - name: video
              persistentVolumeClaim:
                claimName: video
            - name: samba-public
              persistentVolumeClaim:
                claimName: samba-public
            - name: non-public
              persistentVolumeClaim:
                claimName: non-public

          extraVolumeMounts:
            - mountPath: /var/www/html/config/oldinstance.config.php
            # - mountPath: /oldinstance.config.php
              name: oldinstance
              readOnly: true
              subPath: oldinstance.config.php
            - mountPath: /var/www/html/config/oidc.config.php
              name: oidc
              readOnly: true
              subPath: oidc.config.php
            - mountPath: /opt/certs/redis
              name: redis-tls-certs
              readOnly: true
            - mountPath: /data/pictures
              name: pictures
              readOnly: true
              subPath: pictures
            - mountPath: /data/audio
              name: audio
              readOnly: true
              subPath: audio
            - mountPath: /data/video
              name: video
              readOnly: true
              subPath: video
            - mountPath: /data/samba/public
              name: samba-public
              readOnly: true
            - mountPath: /data/non-public
              name: non-public
              readOnly: true

          # Set securityContext parameters for the entire pod. For example, you may need to define runAsNonRoot directive
          podSecurityContext:
            fsGroup: 33
            fsGroupChangePolicy: "OnRootMismatch"
          #   runAsUser: 33
          #   runAsGroup: 33
          #   runAsNonRoot: true
          #   readOnlyRootFilesystem: false

        internalDatabase:
          enabled: false

        ##
        ## External database configuration
        ##
        externalDatabase:
          enabled: true

          ## Supported database engines: mysql or postgresql
          type: mysql

          ## Database host
          host: nextcloud-mariadb.media-files.svc.cluster.local:3306

          ## Database user
          user: nextcloud

          ## Database name
          database: nextcloud

          ## Use a existing secret
          existingSecret:
            enabled: true
            secretName: mariadb-secrets
            usernameKey: mariadb-username
            passwordKey: mariadb-password

        ##
        ## MariaDB chart configuration
        ## ref: https://github.com/bitnami/charts/tree/main/bitnami/mariadb
        ##
        mariadb:
          ## Whether to deploy a mariadb server from the bitnami mariab db helm chart
          # to satisfy the applications database requirements. if you want to deploy this bitnami mariadb, set this and externalDatabase to true
          # To use an ALREADY DEPLOYED mariadb database, set this to false and configure the externalDatabase parameters
          enabled: true

          auth:
            database: nextcloud
            username: nextcloud
            # Use existing secret (auth.rootPassword, auth.password, and auth.replicationPassword will be ignored).
            # secret must contain the keys mariadb-root-password, mariadb-replication-password and mariadb-password
            existingSecret: mariadb-secrets

            ## @param auth.forcePassword Force users to specify required passwords
            ##
            forcePassword: true

          architecture: standalone

          ## Enable persistence using Persistent Volume Claims
          ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
          ##
          primary:
            resourcesPreset: "none"
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                cpu: 375m
                memory: 384Mi
            persistence:
              enabled: true
              # Use an existing Persistent Volume Claim (must be created ahead of time)
              # existingClaim: ""
              storageClass: ceph-block
              accessMode: ReadWriteOnce
              size: 8Gi

            ## @param primary.configuration [string] MariaDB Primary configuration to be injected as ConfigMap
            ## ref: https://mysql.com/kb/en/mysql/configuring-mysql-with-mycnf/#example-of-configuration-file
            ##
            # configuration: |-
            #   [mysqld]
            #   character_set_server = utf8mb4
            #   collation_server = utf8mb4_general_ci
            #   transaction_isolation = READ-COMMITTED
            #   binlog_format = ROW
            #   innodb_large_prefix=on
            #   innodb_file_format=barracuda
            #   innodb_file_per_table=1

        ##
        ## PostgreSQL chart configuration
        ## for more options see https://github.com/bitnami/charts/tree/main/bitnami/postgresql
        ##
        postgresql:
          enabled: false

        ## Enable persistence using Persistent Volume Claims
        ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
        ##
        persistence:
          # Nextcloud Data (/var/www/html)
          enabled: true
          ## nextcloud data Persistent Volume Storage Class
          ## If defined, storageClassName: <storageClass>
          ## If set to "-", storageClassName: "", which disables dynamic provisioning
          ## If undefined (the default) or set to null, no storageClassName spec is
          ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
          ##   GKE, AWS & OpenStack)
          ##
          storageClass: ceph-block
          accessMode: ReadWriteOnce

          # accessMode: ReadWriteMany # has way too long install times
          size: 250Gi

        ##
        ## Redis chart configuration
        ## for more options see https://github.com/bitnami/charts/tree/main/bitnami/redis
        ##

        redis:
          enabled: false

        ## Cronjob to execute Nextcloud background tasks
        ## ref: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron
        ##
        cronjob:
          enabled: true

        ## Liveness and readiness probe values
        ## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
        ##
        startupProbe:
          enabled: true
          initialDelaySeconds: 120 #30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 50 #30
          successThreshold: 1

        ## Prometheus Exporter / Metrics
        ##
        metrics:
          enabled: true

          ## Prometheus Operator ServiceMonitor configuration
          ##
          serviceMonitor:
            ## @param metrics.serviceMonitor.enabled Create ServiceMonitor Resource for scraping metrics using PrometheusOperator
            ##
            enabled: true

```

## Additional context, if any
redis-cluster is deployed seperately with a bitnami chart.
