### ISSUE TITLE
question about transfer from apache image to fpm flavor image

### ISSUE THREAD

**Issue by im-Kitsch** [nextcloud/helm#669]
## Describe your Issue
Hi, firstly thanks for your excellent work. 
I am currently using Helm to deploy Nextcloud on Kubernetes and I would like to switch from Apache to Nginx. I wonder if that is possible or not. And I wanna to ask if there exist specific guidance on how to perform this switch and information about what configurations need to be modified.

### Logs and Errors
No errors to report as this is a preventative inquiry to ensure a smooth transition.

## Describe your Environment

- Kubernetes distribution: rke2

- Helm Version (or App that manages helm): 3.15.3

- Helm Chart Version: 30.0

- `values.yaml`:

```yaml
I think it's not needed
```

## Additional context, if any
I think the essential thing is that the persistence volume is exchangable or not. Looks  configuration yaml fil is exchangable between each other?

**Comment by jessebot** [comment]
Hoi and thank you! As it's a community maintained chart, so also thank you to everyone working on/maintaining this chart :)

Currently all of our documentation for this helm chart is in the chart directory's [`README`](https://github.com/nextcloud/helm/tree/main/charts/nextcloud#quick-links), and here's the section we have on nginx: [Using nginx](https://github.com/nextcloud/helm/tree/main/charts/nextcloud#using-nginx).

The main you points of note you want are that you need to enable:

```yaml
# This Generates an image tag using the chart's app version
# e.g. if the app version is 30.0.0, the image tag will be 30.0.0-fpm
image:
  flavor: fpm
  # You can also specify a tag directly. this version is an example:
  # tag: 30.0.0-fpm

# this deploys an nginx container within the nextcloud pod
nginx
  enabled: true
```

The persistent volume should be the same :)
