### ISSUE TITLE
"Update needed" after upgrade to nextcloud 31

### ISSUE THREAD

**Issue by rafal11ck** [nextcloud/helm#702]
## Describe your Issue

I changed `image.tag` from `tag: 30.0.6-fpm-alpine` to `tag: 31.0.0-fpm-alpine`

Do I just enter container and execute cli update?

### Logs and Errors

Nothing interesting in logs.

## Describe your Environment

- Kubernetes distribution: talos

- Helm Version (or App that manages helm):  fluxcd 2.5.1

- Helm Chart Version:  6.6.6

- `values.yaml`:

```yaml
image:
      flavor: fpm-alpine
      # renovate: datasource=docker depName=registry.hub.docker.com/library/nextcloud
      tag: 31.0.0-fpm-alpine
    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/hostname: &hostname "cloud2.${SECRET_DOMAIN}"
        external-dns.alpha.kubernetes.io/target: "${SECRET_PUBLIC_IP}"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
        # Keep this in sync with the README.md:
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
          rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      path: /
      pathType: Prefix
    nextcloud:
      configs:
        local.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.0.0.0/8',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
            'maintenance_window_start' => 1,
            'default_phone_region' => 'PL',
          );
      host: *hostname
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
    cronjob:
      enabled: true
    nginx:
      enabled: true
      config:
        headers:
          "Strict-Transport-Security": "max-age=15768000; includeSubDomains;"
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-database-app
        usernameKey: user
        passwordKey: password
        hostKey: host
        databaseKey: dbname
    persistence:
      enabled: true
      size: 5Gi
      nextcloudData:
        enabled: true
        size: 5Gi

```

## Additional context, if any

Default storage class is openEBS hostpath

![Image](https://github.com/user-attachments/assets/244080f1-ed4d-4e1a-8952-77ed9a049d77)
