### ISSUE TITLE
Nextcloud Helm Chart not working with JuiceFS

### ISSUE THREAD

**Issue by ok-lux** [nextcloud/helm#711]
## Describe your Issue
I'm trying to install Nextcloud Helm Charts with JuiceFS as persistence, but Nextcloud can't initialize. I can go inside the container, the volume is mounted normally, folders and files are created inside, but nothing else happens, no logs anymore.

### Logs and Errors
kubectl logs:
```
Initializing nextcloud 30.0.5.1 ...
```

## Describe your Environment

- Kubernetes distribution: v1.22.5
- Helm Version: 3.15.3
- Helm Chart Version: 6.6.3
- `values.yaml`:
```yaml
replicaCount: 1

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100G
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
    cert-manager.io/cluster-issuer: "http01-issuer"
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;
      rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
      rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }

  tls:
    - secretName: nextcloud-tls
      hosts:
        - nextcloud-test.example.com
  labels: {}
  path: /
  pathType: Prefix

nextcloud:
  host: nextcloud-test.example.com
  objectStore:
    s3:
      enabled: true
      accessKey: ""
      secretKey: ""
      legacyAuth: false
      host: "s3.example.com"
      ssl: true
      port: "443"
      region: "eu-west-1"
      bucket: "nextcloud"
      prefix: ""
      usePathStyle: false
      autoCreate: false
      storageClass: "STANDARD"
      sse_c_key: ""
      existingSecret: ""
      secretKeys:
        host: ""
        accessKey: ""
        secretKey: ""
        bucket: ""
        sse_c_key: ""

externalDatabase:
  enabled: true
  type: postgresql
  host: ""
  user: nextcloud
  password: ""
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-db-app
    usernameKey: username
    passwordKey: password
    hostKey: host
    databaseKey: dbname

persistence:
  enabled: true
  annotations: {}
  storageClass: "juicefs-csi"
  accessMode: ReadWriteOnce
  size: 8Gi
  nextcloudData:
    enabled: false
    subPath:
    annotations: {}
    accessMode: ReadWriteOnce
    size: 8Gi
```

## Additional context, if any
If accessMode is set to ReadWriteMany nothing changes.
Other storageclasses work without problems, including geesefs, which works fine but is very slow.
