### ISSUE TITLE
Imaginary: `h2non/imaginary:1.2.4` is outdated

### ISSUE THREAD

**Issue by shadow1runner** [nextcloud/helm#722]
Some upstream links:
* https://github.com/h2non/imaginary/issues/410
* https://github.com/h2non/imaginary/issues/128

as well as the [docker hub release history](https://hub.docker.com/r/h2non/imaginary/) show that the imaginary image used **by default** (when the respective value is enabled) are outdated.

Should we change the default vlaue to be sth. along the lines

```yaml
imaginary:
  enabled: true
  image:
    registry: docker.io
    repository: nextcloud/aio-imaginary
    tag: latest
```

Or what's the best way moving forward?
Thanks!
