### ISSUE TITLE
Web uploads stall at >3GB files

### ISSUE THREAD

**Issue by Aetylus** [nextcloud/helm#723]
## Describe your Issue

Attempting to upload a file that is greater than 3GB (even 3GB + 1KB) through the web interface stalls and never completes at the final chunk. I can exec into the container and see the chunks being written to tmp, writing to the datadir/user/uploads, but upload never seems to complete and will hang with a message of "a few seconds left" indefinitely.

![Image](https://github.com/user-attachments/assets/e0b9222f-bd7f-43d2-8d37-4a25c0fd00be)

### Logs and Errors

Snippet of the nginx logs just before the final chunk and after:
```log
10.42.3.50 - - [10/Apr/2025:00:33:17 +0000] "PUT /remote.php/dav/uploads/admin/web-file-upload-1dba1492b43a0d2a/303 HTTP/1.1" 201 0 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:19 +0000] "PUT /remote.php/dav/uploads/admin/web-file-upload-1dba1492b43a0d2a/304 HTTP/1.1" 201 0 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:19 +0000] "PUT /remote.php/dav/uploads/admin/web-file-upload-1dba1492b43a0d2a/306 HTTP/1.1" 201 0 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:19 +0000] "PUT /remote.php/dav/uploads/admin/web-file-upload-1dba1492b43a0d2a/305 HTTP/1.1" 201 0 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:19 +0000] "PUT /remote.php/dav/uploads/admin/web-file-upload-1dba1492b43a0d2a/308 HTTP/1.1" 201 0 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:19 +0000] "PUT /remote.php/dav/uploads/admin/web-file-upload-1dba1492b43a0d2a/307 HTTP/1.1" 201 0 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:21 +0000] "GET /apps/logreader/api/poll?lastReqId=V7UTyLhFLRdBCWwHDtZx HTTP/1.1" 200 22 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:22 +0000] "GET /apps/logreader/api/poll?lastReqId=V7UTyLhFLRdBCWwHDtZx HTTP/1.1" 200 22 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:22 +0000] "POST /apps/text/session/57/sync HTTP/1.1" 200 469 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:24 +0000] "GET /apps/logreader/api/poll?lastReqId=V7UTyLhFLRdBCWwHDtZx HTTP/1.1" 200 22 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:27 +0000] "POST /apps/text/session/57/sync HTTP/1.1" 200 469 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:29 +0000] "POST /apps/text/session/57/push HTTP/1.1" 200 22 "-" "<USER AGENT>" "192.168.0.38"
10.42.3.50 - - [10/Apr/2025:00:33:31 +0000] "GET /apps/logreader/api/poll?lastReqId=V7UTyLhFLRdBCWwHDtZx HTTP/1.1" 200 22 "-" "<USER AGENT>" "192.168.0.38"
```

## Describe your Environment

- Kubernetes distribution: k3s

- Helm Version (or App that manages helm): v3.14.0

- Helm Chart Version:  6.6.9

- `values.yaml`:

```yaml
image:
  flavor: fpm

nextcloud:

![Image](https://github.com/user-attachments/assets/e129806f-e014-4fef-b4e6-270c8dee1db9)

  phpConfigs:
    zz-max_filesize.ini: |-
      upload_max_filesize 10G
      post_max_size 10G
  extraEnv:
    - name: PHP_UPLOAD_LIMIT
      value: 10G
    - name: TMPDIR
      value: /var/www/tmp
  securityContext:
    runAsUser: 33
    runAsGroup: 33
    runAsNonRoot: true

nginx:
  enabled: true
  image:
    repository: nginxinc/nginx-unprivileged
  securityContext:
    runAsUser: 101
    runAsGroup: 33
    runAsNonRoot: true

persistence:
  enabled: true
```

I've truncated non-relevant portions of the `values.yaml`.

## Additional context, if any

As far as I can tell, the `phpConfigs` options don't actually work, and adding or removing it seems to have no effect. I only was able to increase past the 512MB limit by adding the `PHP_UPLOAD_LIMIT=10G` environment variable, which is documented on the Nextcloud Docker container repo, but also notably doesn't actually seemed referenced in any of the `fpm` configuration (`/usr/local/etc/php-fpm*`). This is a bit of a mystery to me.

The following situations do work with files over 3GB:

* Windows mounted network drive through WebDAV (provided the file is also under 4GB due to Windows restrictions)
* `curl --insecure -v -u admin -T <filename> "https://<hostname>/remote.php/dav/files/admin/test_4g.io"`

**Comment by Aetylus** [comment]
After four days of spending my entire evening on this, I believe I've come to a solution. It looks like the default chunking of 10MB for Nextcloud 30 (which is what the Helm chart defaults to) was causing issues. I know Nextcloud 31 changes this default to 100MB, so after changing that setting using `php occ config:app:set files max_chunk_size --value 104857600`, it seemed to have fixed that problem.

It did however introduce a new problem where the Nginx container was receiving a kill signal and restarting in the middle of uploads. After looking into it, it looks like the liveness probe was failing, likely due to the server loads not being able to respond to the status.php requests in time, so I had to increase the timeout from 10 seconds (default). 30 seconds seems to work for me but you may not have to do this if you run into this issue depending on your hardware.

Ultimately, I've added the following to my `values.yaml`:
```yaml
lifecycle:
  # Set max_chunk_size to 100MB
  postStartCommand: ['php', 'occ', 'config:app:set', 'files', 'max_chunk_size', '--value', '104857600']

livenessProbe:
  periodSeconds: 30
  timeoutSeconds: 30
readinessProbe:
  periodSeconds: 30
  timeoutSeconds: 30
```
You don't have to do the lifecycle option if you just set it once, but I figured having it declared like this would mean I wouldn't have to remember it and makes it more reproducible.
