### ISSUE TITLE
Unable to set 'overwriteprotocol' => 'https', in config.php from nextcloud-values.yaml

### ISSUE THREAD

**Issue by refract99** [nextcloud/helm#731]
## Describe your Issue
I need 'overwriteprotocol' => 'https', in my nextcloud config.php in order to use desktop client with my k3s nextcloud.  phpClientHttpsFix doesn't seem to work.

### Logs and Errors
No errors.  Everything works if I manually add "overwriteprotocol..." to the config.php

## Describe your Environment

- Kubernetes distribution: k3s

- Helm Version (or App that manages helm): version.BuildInfo{Version:"v3.16.4", GitCommit:"7877b45b63f95635153b29a42c0c2f4273ec45ca", GitTreeState:"clean", GoVersion:"go1.22.7"}

- Helm Chart Version: 6.6.10

- `values.yaml`:
```yaml
nextcloud:
  host: "<DOMAIN>"
  username: "nc_admin"
  password: "<PASSWORD>"
  redis:
    enabled: true
    host: "nextcloud-redis-master"
    password: '<PASSWORD>'
  config:
    overwriteprotocol: "https"
    trusted_domains:
      - "<DOMAIN>"
      - "localhost"

phpClientHttpsFix:
  enabled: true
  protocol: "https"

replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "10G"
  hosts:
    - host: "<DOMAIN>"
      paths: "/"
      pathType: "Prefix" 
  tls:
    - secretName: <DOMAIN>-tls
      hosts:
        - <DOMAIN>

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 2Ti

internalDatabase:
  enabled: false    

mariadb:
  enabled: true
  auth:
    database: "nextcloud_db"
    username: "nc_user"
    password: '<PASSWORD>'
    rootPassword: '<PASSWORD>'
  architecture: "standalone"
  primary:
    persistence:
      enabled: true
      storageClass: "longhorn"
      accessMode: "ReadWriteOnce"
      size: "10Gi"

redis:
  enabled: true
  auth:
    enabled: true
    password: '<PASSWORD>'
  master:
    persistence:
      enabled: true
      storageClass: "longhorn"
      accessMode: "ReadWriteOnce"
      size: "1Gi"
  replica:
    replicaCount: 0
```
