### ISSUE TITLE
mariadb-isalive container stuck with "ERROR 1045 (28000): Access denied for user..."

### ISSUE THREAD

**Issue by hubwoop** [nextcloud/helm#80]
Hi, I updated the helm chart to 2.5.5 today which led to the following error repeating in the mariadb-isalive container:

`ERROR 1045 (28000): Access denied for user 'nextcloud'@'10.42.0.236' (using password: YES)
waiting for mysql`

Now the DB isn't starting and the pod is stuck in state init 1.

```
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2021-02-16T21:01:20Z'
      message: 'containers with incomplete status: [mariadb-isalive]'
      reason: ContainersNotInitialized
      status: 'False'
      type: Initialized
```

Is there any more data I can provide to help fixing this issue?

**Comment by tvories** [comment]
Can you provide some of your `values` (removing sensitive data)?

**Comment by hubwoop** [comment]
Sure, here you go, thanks for taking the time:

```

image:
  tag: 21-beta

nextcloud:
  host: nextcloud.mydomain.internet
  existingSecret:
    enabled: true
    secretName: nextcloud-helm-chart
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
  phpConfigs: {}
  defaultConfigs:
    .htaccess: true
    redis.config.php: true
    apache-pretty-urls.config.php: true
    apcu.config.php: true
    apps.config.php: true
    autoconfig.php: true
    smtp.config.php: true
  configs:
    https.config.php: |-
      <?php
      $CONFIG = array (
        'overwriteprotocol' => 'https',
      );
  strategy:
    type: Recreate
  extraEnv:
  extraVolumes:
  extraVolumeMounts:
internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: mysql
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-database
    usernameKey: mariadb-username
    passwordKey: mariadb-password
mariadb:
  enabled: true
  existingSecret: nextcloud-database
  db:
    name: nextcloud
    user: nextcloud
  master:
    persistence:
      enabled: true
persistence:
  enabled: true
  annotations: {}
  size: 200Gi
metrics:
  enabled: true
  https: true
  service:
    annotations: {}
    labels:
      app: nextcloud-metrics
```

**Comment by tvories** [comment]
Just to clarify, this was working on release `2.5.4` (or earlier)?

**Comment by hubwoop** [comment]
Yep, we've set the version to 2.5.* in argo-cd so it went to 2.5.5 from 2.5.4 just after the latest release

**Comment by tvories** [comment]
OK, I think I see the issue here. [`2.5.5`](https://github.com/nextcloud/helm/commit/64276b70fd69e37d9b07730be5a33322e9ea0db1) adds a test to validate that MySQL is up before the nextcloud pod starts.  It appears that using an existing secret must not interpolate the value `mariadb.db.password` to the helm chart values.  

I'm not familiar enough with how exactly helm populates that value to the `initContainers` if the value is an existing secret.

I could add a check to the helm template to only run that if the password is defined, but maybe there's a way to incorporate both features.

**Comment by hubwoop** [comment]
Yep, looks like the root cause, I will also look for a solution.

**Comment by tvories** [comment]
I will write up a conditional for the `maria.db.password` check just to have a solution, but it would be nice to look into what's possible.

**Comment by hubwoop** [comment]
Could we use this as a solution?

```
      {{- if .Values.mariadb.enabled }}
      initContainers:
      - name: mariadb-isalive
        image: bitnami/mariadb
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.externalDatabase.existingSecret.secretName | default (printf "%s-%s" .Release.Name "db") }}
                key: {{ .Values.externalDatabase.existingSecret.usernameKey | default "db-username" }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.externalDatabase.existingSecret.secretName | default (printf "%s-%s" .Release.Name "db") }}
                key: {{ .Values.externalDatabase.existingSecret.passwordKey | default "db-password" }}
        command:
          - "sh"
          - "-c"
          - {{ printf "until mysql --host=%s-mariadb --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute=\"SELECT 1;\"; do echo waiting for mysql; sleep 2; done;" .Release.Name }}
      {{- end }}
```
