### ISSUE TITLE
postgresql-isready breaks installations on arm64

### ISSUE THREAD

**Issue by francesco995** [nextcloud/helm#94]
HI,
the new init container postgresql-isready does not work on arm64 architecture

kubectl logs -f  nextcloud-566d5c5459-gxl99 -c postgresql-isready
standard_init_linux.go:219: exec user process caused: exec format error

is it possible to at least make the init container optional with a values.yaml flag?

**Comment by tvories** [comment]
@francesco995 are you using postgresql on arm64?  What image are you using for it?

**Comment by Couto** [comment]
@tvories I'm not OP, but I'm hitting the exact  same problem.

```
postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: postgres
    tag: 13.1
  global:
    postgresql:
      postgresqlUsername: nextcloud
      postgresqlPassword: <REDACTED>
      postgresqlDatabase: nextcloud
  persistence:
    enabled: true
    storageClass: nfs-client
```

So far, from what I've seen, only the nextcloud image actually supports arm64, both mariadb and postgresql from bitnami don't seem to support arm64 at all.

I'm not familiar with those images, but why are they preferred to the official ones?
