### ISSUE TITLE
Hardcoded initContainer image name

### ISSUE THREAD

**Issue by krisko** [nextcloud/helm#99]
Please don't hardcode image names into helm chart. 
I use custom postgresql image, because bitnami doesn't support armv8.

values.yaml:
```
postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: postgres
    tag: 11.1
```

Helm chart should respect custom image values.

Introduced in: https://github.com/nextcloud/helm/commit/8c75469b2a617279f35008f72aa1aa5b93341faa
